// Code generated by ent, DO NOT EDIT.

package deliveryattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/0xLaiHo/rc_tobias/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLTE(FieldID, id))
}

// NotificationID applies equality check predicate on the "notification_id" field. It's identical to NotificationIDEQ.
func NotificationID(v uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldNotificationID, v))
}

// AttemptNumber applies equality check predicate on the "attempt_number" field. It's identical to AttemptNumberEQ.
func AttemptNumber(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldAttemptNumber, v))
}

// HTTPStatus applies equality check predicate on the "http_status" field. It's identical to HTTPStatusEQ.
func HTTPStatus(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldHTTPStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldErrorMessage, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldDurationMs, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// NotificationIDEQ applies the EQ predicate on the "notification_id" field.
func NotificationIDEQ(v uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldNotificationID, v))
}

// NotificationIDNEQ applies the NEQ predicate on the "notification_id" field.
func NotificationIDNEQ(v uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNEQ(FieldNotificationID, v))
}

// NotificationIDIn applies the In predicate on the "notification_id" field.
func NotificationIDIn(vs ...uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIn(FieldNotificationID, vs...))
}

// NotificationIDNotIn applies the NotIn predicate on the "notification_id" field.
func NotificationIDNotIn(vs ...uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotIn(FieldNotificationID, vs...))
}

// NotificationIDGT applies the GT predicate on the "notification_id" field.
func NotificationIDGT(v uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGT(FieldNotificationID, v))
}

// NotificationIDGTE applies the GTE predicate on the "notification_id" field.
func NotificationIDGTE(v uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGTE(FieldNotificationID, v))
}

// NotificationIDLT applies the LT predicate on the "notification_id" field.
func NotificationIDLT(v uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLT(FieldNotificationID, v))
}

// NotificationIDLTE applies the LTE predicate on the "notification_id" field.
func NotificationIDLTE(v uuid.UUID) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLTE(FieldNotificationID, v))
}

// AttemptNumberEQ applies the EQ predicate on the "attempt_number" field.
func AttemptNumberEQ(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldAttemptNumber, v))
}

// AttemptNumberNEQ applies the NEQ predicate on the "attempt_number" field.
func AttemptNumberNEQ(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNEQ(FieldAttemptNumber, v))
}

// AttemptNumberIn applies the In predicate on the "attempt_number" field.
func AttemptNumberIn(vs ...int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIn(FieldAttemptNumber, vs...))
}

// AttemptNumberNotIn applies the NotIn predicate on the "attempt_number" field.
func AttemptNumberNotIn(vs ...int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotIn(FieldAttemptNumber, vs...))
}

// AttemptNumberGT applies the GT predicate on the "attempt_number" field.
func AttemptNumberGT(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGT(FieldAttemptNumber, v))
}

// AttemptNumberGTE applies the GTE predicate on the "attempt_number" field.
func AttemptNumberGTE(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGTE(FieldAttemptNumber, v))
}

// AttemptNumberLT applies the LT predicate on the "attempt_number" field.
func AttemptNumberLT(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLT(FieldAttemptNumber, v))
}

// AttemptNumberLTE applies the LTE predicate on the "attempt_number" field.
func AttemptNumberLTE(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLTE(FieldAttemptNumber, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotIn(FieldStatus, vs...))
}

// HTTPStatusEQ applies the EQ predicate on the "http_status" field.
func HTTPStatusEQ(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldHTTPStatus, v))
}

// HTTPStatusNEQ applies the NEQ predicate on the "http_status" field.
func HTTPStatusNEQ(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNEQ(FieldHTTPStatus, v))
}

// HTTPStatusIn applies the In predicate on the "http_status" field.
func HTTPStatusIn(vs ...int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIn(FieldHTTPStatus, vs...))
}

// HTTPStatusNotIn applies the NotIn predicate on the "http_status" field.
func HTTPStatusNotIn(vs ...int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotIn(FieldHTTPStatus, vs...))
}

// HTTPStatusGT applies the GT predicate on the "http_status" field.
func HTTPStatusGT(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGT(FieldHTTPStatus, v))
}

// HTTPStatusGTE applies the GTE predicate on the "http_status" field.
func HTTPStatusGTE(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGTE(FieldHTTPStatus, v))
}

// HTTPStatusLT applies the LT predicate on the "http_status" field.
func HTTPStatusLT(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLT(FieldHTTPStatus, v))
}

// HTTPStatusLTE applies the LTE predicate on the "http_status" field.
func HTTPStatusLTE(v int) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLTE(FieldHTTPStatus, v))
}

// HTTPStatusIsNil applies the IsNil predicate on the "http_status" field.
func HTTPStatusIsNil() predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIsNull(FieldHTTPStatus))
}

// HTTPStatusNotNil applies the NotNil predicate on the "http_status" field.
func HTTPStatusNotNil() predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotNull(FieldHTTPStatus))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldContainsFold(FieldErrorMessage, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLTE(FieldDurationMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeliveryAttempt) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeliveryAttempt) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeliveryAttempt) predicate.DeliveryAttempt {
	return predicate.DeliveryAttempt(sql.NotPredicates(p))
}
