// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DeliveryAttemptsColumns holds the columns for the "delivery_attempts" table.
	DeliveryAttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "notification_id", Type: field.TypeUUID},
		{Name: "attempt_number", Type: field.TypeInt},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"succeeded", "retrying", "failed"}},
		{Name: "http_status", Type: field.TypeInt, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// DeliveryAttemptsTable holds the schema information for the "delivery_attempts" table.
	DeliveryAttemptsTable = &schema.Table{
		Name:       "delivery_attempts",
		Columns:    DeliveryAttemptsColumns,
		PrimaryKey: []*schema.Column{DeliveryAttemptsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "deliveryattempt_notification_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{DeliveryAttemptsColumns[1], DeliveryAttemptsColumns[7]},
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "url", Type: field.TypeString},
		{Name: "method", Type: field.TypeString, Default: "POST"},
		{Name: "headers", Type: field.TypeJSON, Nullable: true},
		{Name: "body", Type: field.TypeBytes, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "delivering", "succeeded", "retrying", "failed"}, Default: "pending"},
		{Name: "attempt_count", Type: field.TypeInt, Default: 0},
		{Name: "max_attempts", Type: field.TypeInt, Default: 5},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "next_attempt_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
	}
	// OutboxEventsColumns holds the columns for the "outbox_events" table.
	OutboxEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "notification_id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeString, Default: "notification.delivery_requested"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "publishing", "published", "failed"}, Default: "pending"},
		{Name: "scheduled_at", Type: field.TypeTime},
		{Name: "stream_id", Type: field.TypeString, Nullable: true},
		{Name: "locked_by", Type: field.TypeString, Nullable: true},
		{Name: "locked_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OutboxEventsTable holds the schema information for the "outbox_events" table.
	OutboxEventsTable = &schema.Table{
		Name:       "outbox_events",
		Columns:    OutboxEventsColumns,
		PrimaryKey: []*schema.Column{OutboxEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "outboxevent_scheduled_at_created_at",
				Unique:  false,
				Columns: []*schema.Column{OutboxEventsColumns[4], OutboxEventsColumns[10]},
				Annotation: &entsql.IndexAnnotation{
					Where: "status IN ('pending', 'publishing')",
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DeliveryAttemptsTable,
		NotificationsTable,
		OutboxEventsTable,
	}
)

func init() {
	DeliveryAttemptsTable.Annotation = &entsql.Annotation{
		Table: "delivery_attempts",
	}
	NotificationsTable.Annotation = &entsql.Annotation{
		Table: "notifications",
	}
	OutboxEventsTable.Annotation = &entsql.Annotation{
		Table: "outbox_events",
	}
}
