// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/0xLaiHo/rc_tobias/ent/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/0xLaiHo/rc_tobias/ent/deliveryattempt"
	"github.com/0xLaiHo/rc_tobias/ent/notification"
	"github.com/0xLaiHo/rc_tobias/ent/outboxevent"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DeliveryAttempt is the client for interacting with the DeliveryAttempt builders.
	DeliveryAttempt *DeliveryAttemptClient
	// Notification is the client for interacting with the Notification builders.
	Notification *NotificationClient
	// OutboxEvent is the client for interacting with the OutboxEvent builders.
	OutboxEvent *OutboxEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DeliveryAttempt = NewDeliveryAttemptClient(c.config)
	c.Notification = NewNotificationClient(c.config)
	c.OutboxEvent = NewOutboxEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		DeliveryAttempt: NewDeliveryAttemptClient(cfg),
		Notification:    NewNotificationClient(cfg),
		OutboxEvent:     NewOutboxEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		DeliveryAttempt: NewDeliveryAttemptClient(cfg),
		Notification:    NewNotificationClient(cfg),
		OutboxEvent:     NewOutboxEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DeliveryAttempt.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DeliveryAttempt.Use(hooks...)
	c.Notification.Use(hooks...)
	c.OutboxEvent.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.DeliveryAttempt.Intercept(interceptors...)
	c.Notification.Intercept(interceptors...)
	c.OutboxEvent.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DeliveryAttemptMutation:
		return c.DeliveryAttempt.mutate(ctx, m)
	case *NotificationMutation:
		return c.Notification.mutate(ctx, m)
	case *OutboxEventMutation:
		return c.OutboxEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DeliveryAttemptClient is a client for the DeliveryAttempt schema.
type DeliveryAttemptClient struct {
	config
}

// NewDeliveryAttemptClient returns a client for the DeliveryAttempt from the given config.
func NewDeliveryAttemptClient(c config) *DeliveryAttemptClient {
	return &DeliveryAttemptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `deliveryattempt.Hooks(f(g(h())))`.
func (c *DeliveryAttemptClient) Use(hooks ...Hook) {
	c.hooks.DeliveryAttempt = append(c.hooks.DeliveryAttempt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `deliveryattempt.Intercept(f(g(h())))`.
func (c *DeliveryAttemptClient) Intercept(interceptors ...Interceptor) {
	c.inters.DeliveryAttempt = append(c.inters.DeliveryAttempt, interceptors...)
}

// Create returns a builder for creating a DeliveryAttempt entity.
func (c *DeliveryAttemptClient) Create() *DeliveryAttemptCreate {
	mutation := newDeliveryAttemptMutation(c.config, OpCreate)
	return &DeliveryAttemptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DeliveryAttempt entities.
func (c *DeliveryAttemptClient) CreateBulk(builders ...*DeliveryAttemptCreate) *DeliveryAttemptCreateBulk {
	return &DeliveryAttemptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeliveryAttemptClient) MapCreateBulk(slice any, setFunc func(*DeliveryAttemptCreate, int)) *DeliveryAttemptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeliveryAttemptCreateBulk{err: fmt.Errorf("calling to DeliveryAttemptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeliveryAttemptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeliveryAttemptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DeliveryAttempt.
func (c *DeliveryAttemptClient) Update() *DeliveryAttemptUpdate {
	mutation := newDeliveryAttemptMutation(c.config, OpUpdate)
	return &DeliveryAttemptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeliveryAttemptClient) UpdateOne(_m *DeliveryAttempt) *DeliveryAttemptUpdateOne {
	mutation := newDeliveryAttemptMutation(c.config, OpUpdateOne, withDeliveryAttempt(_m))
	return &DeliveryAttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeliveryAttemptClient) UpdateOneID(id uuid.UUID) *DeliveryAttemptUpdateOne {
	mutation := newDeliveryAttemptMutation(c.config, OpUpdateOne, withDeliveryAttemptID(id))
	return &DeliveryAttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DeliveryAttempt.
func (c *DeliveryAttemptClient) Delete() *DeliveryAttemptDelete {
	mutation := newDeliveryAttemptMutation(c.config, OpDelete)
	return &DeliveryAttemptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeliveryAttemptClient) DeleteOne(_m *DeliveryAttempt) *DeliveryAttemptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeliveryAttemptClient) DeleteOneID(id uuid.UUID) *DeliveryAttemptDeleteOne {
	builder := c.Delete().Where(deliveryattempt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeliveryAttemptDeleteOne{builder}
}

// Query returns a query builder for DeliveryAttempt.
func (c *DeliveryAttemptClient) Query() *DeliveryAttemptQuery {
	return &DeliveryAttemptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeliveryAttempt},
		inters: c.Interceptors(),
	}
}

// Get returns a DeliveryAttempt entity by its id.
func (c *DeliveryAttemptClient) Get(ctx context.Context, id uuid.UUID) (*DeliveryAttempt, error) {
	return c.Query().Where(deliveryattempt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeliveryAttemptClient) GetX(ctx context.Context, id uuid.UUID) *DeliveryAttempt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeliveryAttemptClient) Hooks() []Hook {
	return c.hooks.DeliveryAttempt
}

// Interceptors returns the client interceptors.
func (c *DeliveryAttemptClient) Interceptors() []Interceptor {
	return c.inters.DeliveryAttempt
}

func (c *DeliveryAttemptClient) mutate(ctx context.Context, m *DeliveryAttemptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeliveryAttemptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeliveryAttemptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeliveryAttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeliveryAttemptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DeliveryAttempt mutation op: %q", m.Op())
	}
}

// NotificationClient is a client for the Notification schema.
type NotificationClient struct {
	config
}

// NewNotificationClient returns a client for the Notification from the given config.
func NewNotificationClient(c config) *NotificationClient {
	return &NotificationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notification.Hooks(f(g(h())))`.
func (c *NotificationClient) Use(hooks ...Hook) {
	c.hooks.Notification = append(c.hooks.Notification, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notification.Intercept(f(g(h())))`.
func (c *NotificationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Notification = append(c.inters.Notification, interceptors...)
}

// Create returns a builder for creating a Notification entity.
func (c *NotificationClient) Create() *NotificationCreate {
	mutation := newNotificationMutation(c.config, OpCreate)
	return &NotificationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Notification entities.
func (c *NotificationClient) CreateBulk(builders ...*NotificationCreate) *NotificationCreateBulk {
	return &NotificationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationClient) MapCreateBulk(slice any, setFunc func(*NotificationCreate, int)) *NotificationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationCreateBulk{err: fmt.Errorf("calling to NotificationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Notification.
func (c *NotificationClient) Update() *NotificationUpdate {
	mutation := newNotificationMutation(c.config, OpUpdate)
	return &NotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationClient) UpdateOne(_m *Notification) *NotificationUpdateOne {
	mutation := newNotificationMutation(c.config, OpUpdateOne, withNotification(_m))
	return &NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationClient) UpdateOneID(id uuid.UUID) *NotificationUpdateOne {
	mutation := newNotificationMutation(c.config, OpUpdateOne, withNotificationID(id))
	return &NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Notification.
func (c *NotificationClient) Delete() *NotificationDelete {
	mutation := newNotificationMutation(c.config, OpDelete)
	return &NotificationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationClient) DeleteOne(_m *Notification) *NotificationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationClient) DeleteOneID(id uuid.UUID) *NotificationDeleteOne {
	builder := c.Delete().Where(notification.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationDeleteOne{builder}
}

// Query returns a query builder for Notification.
func (c *NotificationClient) Query() *NotificationQuery {
	return &NotificationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotification},
		inters: c.Interceptors(),
	}
}

// Get returns a Notification entity by its id.
func (c *NotificationClient) Get(ctx context.Context, id uuid.UUID) (*Notification, error) {
	return c.Query().Where(notification.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationClient) GetX(ctx context.Context, id uuid.UUID) *Notification {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NotificationClient) Hooks() []Hook {
	return c.hooks.Notification
}

// Interceptors returns the client interceptors.
func (c *NotificationClient) Interceptors() []Interceptor {
	return c.inters.Notification
}

func (c *NotificationClient) mutate(ctx context.Context, m *NotificationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Notification mutation op: %q", m.Op())
	}
}

// OutboxEventClient is a client for the OutboxEvent schema.
type OutboxEventClient struct {
	config
}

// NewOutboxEventClient returns a client for the OutboxEvent from the given config.
func NewOutboxEventClient(c config) *OutboxEventClient {
	return &OutboxEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `outboxevent.Hooks(f(g(h())))`.
func (c *OutboxEventClient) Use(hooks ...Hook) {
	c.hooks.OutboxEvent = append(c.hooks.OutboxEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `outboxevent.Intercept(f(g(h())))`.
func (c *OutboxEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.OutboxEvent = append(c.inters.OutboxEvent, interceptors...)
}

// Create returns a builder for creating a OutboxEvent entity.
func (c *OutboxEventClient) Create() *OutboxEventCreate {
	mutation := newOutboxEventMutation(c.config, OpCreate)
	return &OutboxEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OutboxEvent entities.
func (c *OutboxEventClient) CreateBulk(builders ...*OutboxEventCreate) *OutboxEventCreateBulk {
	return &OutboxEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OutboxEventClient) MapCreateBulk(slice any, setFunc func(*OutboxEventCreate, int)) *OutboxEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OutboxEventCreateBulk{err: fmt.Errorf("calling to OutboxEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OutboxEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OutboxEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OutboxEvent.
func (c *OutboxEventClient) Update() *OutboxEventUpdate {
	mutation := newOutboxEventMutation(c.config, OpUpdate)
	return &OutboxEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OutboxEventClient) UpdateOne(_m *OutboxEvent) *OutboxEventUpdateOne {
	mutation := newOutboxEventMutation(c.config, OpUpdateOne, withOutboxEvent(_m))
	return &OutboxEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OutboxEventClient) UpdateOneID(id uuid.UUID) *OutboxEventUpdateOne {
	mutation := newOutboxEventMutation(c.config, OpUpdateOne, withOutboxEventID(id))
	return &OutboxEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OutboxEvent.
func (c *OutboxEventClient) Delete() *OutboxEventDelete {
	mutation := newOutboxEventMutation(c.config, OpDelete)
	return &OutboxEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OutboxEventClient) DeleteOne(_m *OutboxEvent) *OutboxEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OutboxEventClient) DeleteOneID(id uuid.UUID) *OutboxEventDeleteOne {
	builder := c.Delete().Where(outboxevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OutboxEventDeleteOne{builder}
}

// Query returns a query builder for OutboxEvent.
func (c *OutboxEventClient) Query() *OutboxEventQuery {
	return &OutboxEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOutboxEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a OutboxEvent entity by its id.
func (c *OutboxEventClient) Get(ctx context.Context, id uuid.UUID) (*OutboxEvent, error) {
	return c.Query().Where(outboxevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OutboxEventClient) GetX(ctx context.Context, id uuid.UUID) *OutboxEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OutboxEventClient) Hooks() []Hook {
	return c.hooks.OutboxEvent
}

// Interceptors returns the client interceptors.
func (c *OutboxEventClient) Interceptors() []Interceptor {
	return c.inters.OutboxEvent
}

func (c *OutboxEventClient) mutate(ctx context.Context, m *OutboxEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OutboxEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OutboxEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OutboxEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OutboxEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OutboxEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		DeliveryAttempt, Notification, OutboxEvent []ent.Hook
	}
	inters struct {
		DeliveryAttempt, Notification, OutboxEvent []ent.Interceptor
	}
)
