// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0xLaiHo/rc_tobias/ent/deliveryattempt"
	"github.com/google/uuid"
)

// DeliveryAttemptCreate is the builder for creating a DeliveryAttempt entity.
type DeliveryAttemptCreate struct {
	config
	mutation *DeliveryAttemptMutation
	hooks    []Hook
}

// SetNotificationID sets the "notification_id" field.
func (_c *DeliveryAttemptCreate) SetNotificationID(v uuid.UUID) *DeliveryAttemptCreate {
	_c.mutation.SetNotificationID(v)
	return _c
}

// SetAttemptNumber sets the "attempt_number" field.
func (_c *DeliveryAttemptCreate) SetAttemptNumber(v int) *DeliveryAttemptCreate {
	_c.mutation.SetAttemptNumber(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeliveryAttemptCreate) SetStatus(v deliveryattempt.Status) *DeliveryAttemptCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetHTTPStatus sets the "http_status" field.
func (_c *DeliveryAttemptCreate) SetHTTPStatus(v int) *DeliveryAttemptCreate {
	_c.mutation.SetHTTPStatus(v)
	return _c
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_c *DeliveryAttemptCreate) SetNillableHTTPStatus(v *int) *DeliveryAttemptCreate {
	if v != nil {
		_c.SetHTTPStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *DeliveryAttemptCreate) SetErrorMessage(v string) *DeliveryAttemptCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *DeliveryAttemptCreate) SetNillableErrorMessage(v *string) *DeliveryAttemptCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *DeliveryAttemptCreate) SetDurationMs(v int64) *DeliveryAttemptCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *DeliveryAttemptCreate) SetNillableDurationMs(v *int64) *DeliveryAttemptCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeliveryAttemptCreate) SetCreatedAt(v time.Time) *DeliveryAttemptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeliveryAttemptCreate) SetNillableCreatedAt(v *time.Time) *DeliveryAttemptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeliveryAttemptCreate) SetID(v uuid.UUID) *DeliveryAttemptCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DeliveryAttemptCreate) SetNillableID(v *uuid.UUID) *DeliveryAttemptCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DeliveryAttemptMutation object of the builder.
func (_c *DeliveryAttemptCreate) Mutation() *DeliveryAttemptMutation {
	return _c.mutation
}

// Save creates the DeliveryAttempt in the database.
func (_c *DeliveryAttemptCreate) Save(ctx context.Context) (*DeliveryAttempt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeliveryAttemptCreate) SaveX(ctx context.Context) *DeliveryAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeliveryAttemptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeliveryAttemptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeliveryAttemptCreate) defaults() {
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := deliveryattempt.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deliveryattempt.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := deliveryattempt.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeliveryAttemptCreate) check() error {
	if _, ok := _c.mutation.NotificationID(); !ok {
		return &ValidationError{Name: "notification_id", err: errors.New(`ent: missing required field "DeliveryAttempt.notification_id"`)}
	}
	if _, ok := _c.mutation.AttemptNumber(); !ok {
		return &ValidationError{Name: "attempt_number", err: errors.New(`ent: missing required field "DeliveryAttempt.attempt_number"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DeliveryAttempt.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := deliveryattempt.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DeliveryAttempt.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "DeliveryAttempt.duration_ms"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeliveryAttempt.created_at"`)}
	}
	return nil
}

func (_c *DeliveryAttemptCreate) sqlSave(ctx context.Context) (*DeliveryAttempt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeliveryAttemptCreate) createSpec() (*DeliveryAttempt, *sqlgraph.CreateSpec) {
	var (
		_node = &DeliveryAttempt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deliveryattempt.Table, sqlgraph.NewFieldSpec(deliveryattempt.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.NotificationID(); ok {
		_spec.SetField(deliveryattempt.FieldNotificationID, field.TypeUUID, value)
		_node.NotificationID = value
	}
	if value, ok := _c.mutation.AttemptNumber(); ok {
		_spec.SetField(deliveryattempt.FieldAttemptNumber, field.TypeInt, value)
		_node.AttemptNumber = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(deliveryattempt.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.HTTPStatus(); ok {
		_spec.SetField(deliveryattempt.FieldHTTPStatus, field.TypeInt, value)
		_node.HTTPStatus = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(deliveryattempt.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(deliveryattempt.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deliveryattempt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DeliveryAttemptCreateBulk is the builder for creating many DeliveryAttempt entities in bulk.
type DeliveryAttemptCreateBulk struct {
	config
	err      error
	builders []*DeliveryAttemptCreate
}

// Save creates the DeliveryAttempt entities in the database.
func (_c *DeliveryAttemptCreateBulk) Save(ctx context.Context) ([]*DeliveryAttempt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeliveryAttempt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeliveryAttemptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeliveryAttemptCreateBulk) SaveX(ctx context.Context) []*DeliveryAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeliveryAttemptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeliveryAttemptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
