// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/0xLaiHo/rc_tobias/ent/deliveryattempt"
	"github.com/google/uuid"
)

// DeliveryAttempt is the model entity for the DeliveryAttempt schema.
type DeliveryAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// NotificationID holds the value of the "notification_id" field.
	NotificationID uuid.UUID `json:"notification_id,omitempty"`
	// AttemptNumber holds the value of the "attempt_number" field.
	AttemptNumber int `json:"attempt_number,omitempty"`
	// Status holds the value of the "status" field.
	Status deliveryattempt.Status `json:"status,omitempty"`
	// HTTPStatus holds the value of the "http_status" field.
	HTTPStatus int `json:"http_status,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int64 `json:"duration_ms,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeliveryAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deliveryattempt.FieldAttemptNumber, deliveryattempt.FieldHTTPStatus, deliveryattempt.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case deliveryattempt.FieldStatus, deliveryattempt.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case deliveryattempt.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case deliveryattempt.FieldID, deliveryattempt.FieldNotificationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeliveryAttempt fields.
func (_m *DeliveryAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deliveryattempt.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case deliveryattempt.FieldNotificationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field notification_id", values[i])
			} else if value != nil {
				_m.NotificationID = *value
			}
		case deliveryattempt.FieldAttemptNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_number", values[i])
			} else if value.Valid {
				_m.AttemptNumber = int(value.Int64)
			}
		case deliveryattempt.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = deliveryattempt.Status(value.String)
			}
		case deliveryattempt.FieldHTTPStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status", values[i])
			} else if value.Valid {
				_m.HTTPStatus = int(value.Int64)
			}
		case deliveryattempt.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case deliveryattempt.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Int64
			}
		case deliveryattempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeliveryAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *DeliveryAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DeliveryAttempt.
// Note that you need to call DeliveryAttempt.Unwrap() before calling this method if this DeliveryAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeliveryAttempt) Update() *DeliveryAttemptUpdateOne {
	return NewDeliveryAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeliveryAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeliveryAttempt) Unwrap() *DeliveryAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeliveryAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeliveryAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("DeliveryAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("notification_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotificationID))
	builder.WriteString(", ")
	builder.WriteString("attempt_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNumber))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("http_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.HTTPStatus))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeliveryAttempts is a parsable slice of DeliveryAttempt.
type DeliveryAttempts []*DeliveryAttempt
