// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0xLaiHo/rc_tobias/ent/deliveryattempt"
	"github.com/0xLaiHo/rc_tobias/ent/predicate"
	"github.com/google/uuid"
)

// DeliveryAttemptUpdate is the builder for updating DeliveryAttempt entities.
type DeliveryAttemptUpdate struct {
	config
	hooks    []Hook
	mutation *DeliveryAttemptMutation
}

// Where appends a list predicates to the DeliveryAttemptUpdate builder.
func (_u *DeliveryAttemptUpdate) Where(ps ...predicate.DeliveryAttempt) *DeliveryAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNotificationID sets the "notification_id" field.
func (_u *DeliveryAttemptUpdate) SetNotificationID(v uuid.UUID) *DeliveryAttemptUpdate {
	_u.mutation.SetNotificationID(v)
	return _u
}

// SetNillableNotificationID sets the "notification_id" field if the given value is not nil.
func (_u *DeliveryAttemptUpdate) SetNillableNotificationID(v *uuid.UUID) *DeliveryAttemptUpdate {
	if v != nil {
		_u.SetNotificationID(*v)
	}
	return _u
}

// SetAttemptNumber sets the "attempt_number" field.
func (_u *DeliveryAttemptUpdate) SetAttemptNumber(v int) *DeliveryAttemptUpdate {
	_u.mutation.ResetAttemptNumber()
	_u.mutation.SetAttemptNumber(v)
	return _u
}

// SetNillableAttemptNumber sets the "attempt_number" field if the given value is not nil.
func (_u *DeliveryAttemptUpdate) SetNillableAttemptNumber(v *int) *DeliveryAttemptUpdate {
	if v != nil {
		_u.SetAttemptNumber(*v)
	}
	return _u
}

// AddAttemptNumber adds value to the "attempt_number" field.
func (_u *DeliveryAttemptUpdate) AddAttemptNumber(v int) *DeliveryAttemptUpdate {
	_u.mutation.AddAttemptNumber(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeliveryAttemptUpdate) SetStatus(v deliveryattempt.Status) *DeliveryAttemptUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeliveryAttemptUpdate) SetNillableStatus(v *deliveryattempt.Status) *DeliveryAttemptUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *DeliveryAttemptUpdate) SetHTTPStatus(v int) *DeliveryAttemptUpdate {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *DeliveryAttemptUpdate) SetNillableHTTPStatus(v *int) *DeliveryAttemptUpdate {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *DeliveryAttemptUpdate) AddHTTPStatus(v int) *DeliveryAttemptUpdate {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (_u *DeliveryAttemptUpdate) ClearHTTPStatus() *DeliveryAttemptUpdate {
	_u.mutation.ClearHTTPStatus()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DeliveryAttemptUpdate) SetErrorMessage(v string) *DeliveryAttemptUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DeliveryAttemptUpdate) SetNillableErrorMessage(v *string) *DeliveryAttemptUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DeliveryAttemptUpdate) ClearErrorMessage() *DeliveryAttemptUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *DeliveryAttemptUpdate) SetDurationMs(v int64) *DeliveryAttemptUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *DeliveryAttemptUpdate) SetNillableDurationMs(v *int64) *DeliveryAttemptUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *DeliveryAttemptUpdate) AddDurationMs(v int64) *DeliveryAttemptUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// Mutation returns the DeliveryAttemptMutation object of the builder.
func (_u *DeliveryAttemptUpdate) Mutation() *DeliveryAttemptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeliveryAttemptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeliveryAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeliveryAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeliveryAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeliveryAttemptUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := deliveryattempt.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DeliveryAttempt.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DeliveryAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deliveryattempt.Table, deliveryattempt.Columns, sqlgraph.NewFieldSpec(deliveryattempt.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NotificationID(); ok {
		_spec.SetField(deliveryattempt.FieldNotificationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.AttemptNumber(); ok {
		_spec.SetField(deliveryattempt.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNumber(); ok {
		_spec.AddField(deliveryattempt.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deliveryattempt.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(deliveryattempt.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(deliveryattempt.FieldHTTPStatus, field.TypeInt, value)
	}
	if _u.mutation.HTTPStatusCleared() {
		_spec.ClearField(deliveryattempt.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(deliveryattempt.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(deliveryattempt.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(deliveryattempt.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(deliveryattempt.FieldDurationMs, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deliveryattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeliveryAttemptUpdateOne is the builder for updating a single DeliveryAttempt entity.
type DeliveryAttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeliveryAttemptMutation
}

// SetNotificationID sets the "notification_id" field.
func (_u *DeliveryAttemptUpdateOne) SetNotificationID(v uuid.UUID) *DeliveryAttemptUpdateOne {
	_u.mutation.SetNotificationID(v)
	return _u
}

// SetNillableNotificationID sets the "notification_id" field if the given value is not nil.
func (_u *DeliveryAttemptUpdateOne) SetNillableNotificationID(v *uuid.UUID) *DeliveryAttemptUpdateOne {
	if v != nil {
		_u.SetNotificationID(*v)
	}
	return _u
}

// SetAttemptNumber sets the "attempt_number" field.
func (_u *DeliveryAttemptUpdateOne) SetAttemptNumber(v int) *DeliveryAttemptUpdateOne {
	_u.mutation.ResetAttemptNumber()
	_u.mutation.SetAttemptNumber(v)
	return _u
}

// SetNillableAttemptNumber sets the "attempt_number" field if the given value is not nil.
func (_u *DeliveryAttemptUpdateOne) SetNillableAttemptNumber(v *int) *DeliveryAttemptUpdateOne {
	if v != nil {
		_u.SetAttemptNumber(*v)
	}
	return _u
}

// AddAttemptNumber adds value to the "attempt_number" field.
func (_u *DeliveryAttemptUpdateOne) AddAttemptNumber(v int) *DeliveryAttemptUpdateOne {
	_u.mutation.AddAttemptNumber(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeliveryAttemptUpdateOne) SetStatus(v deliveryattempt.Status) *DeliveryAttemptUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeliveryAttemptUpdateOne) SetNillableStatus(v *deliveryattempt.Status) *DeliveryAttemptUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *DeliveryAttemptUpdateOne) SetHTTPStatus(v int) *DeliveryAttemptUpdateOne {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *DeliveryAttemptUpdateOne) SetNillableHTTPStatus(v *int) *DeliveryAttemptUpdateOne {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *DeliveryAttemptUpdateOne) AddHTTPStatus(v int) *DeliveryAttemptUpdateOne {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (_u *DeliveryAttemptUpdateOne) ClearHTTPStatus() *DeliveryAttemptUpdateOne {
	_u.mutation.ClearHTTPStatus()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DeliveryAttemptUpdateOne) SetErrorMessage(v string) *DeliveryAttemptUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DeliveryAttemptUpdateOne) SetNillableErrorMessage(v *string) *DeliveryAttemptUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DeliveryAttemptUpdateOne) ClearErrorMessage() *DeliveryAttemptUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *DeliveryAttemptUpdateOne) SetDurationMs(v int64) *DeliveryAttemptUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *DeliveryAttemptUpdateOne) SetNillableDurationMs(v *int64) *DeliveryAttemptUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *DeliveryAttemptUpdateOne) AddDurationMs(v int64) *DeliveryAttemptUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// Mutation returns the DeliveryAttemptMutation object of the builder.
func (_u *DeliveryAttemptUpdateOne) Mutation() *DeliveryAttemptMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeliveryAttemptUpdate builder.
func (_u *DeliveryAttemptUpdateOne) Where(ps ...predicate.DeliveryAttempt) *DeliveryAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeliveryAttemptUpdateOne) Select(field string, fields ...string) *DeliveryAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeliveryAttempt entity.
func (_u *DeliveryAttemptUpdateOne) Save(ctx context.Context) (*DeliveryAttempt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeliveryAttemptUpdateOne) SaveX(ctx context.Context) *DeliveryAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeliveryAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeliveryAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeliveryAttemptUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := deliveryattempt.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DeliveryAttempt.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DeliveryAttemptUpdateOne) sqlSave(ctx context.Context) (_node *DeliveryAttempt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deliveryattempt.Table, deliveryattempt.Columns, sqlgraph.NewFieldSpec(deliveryattempt.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeliveryAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deliveryattempt.FieldID)
		for _, f := range fields {
			if !deliveryattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deliveryattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NotificationID(); ok {
		_spec.SetField(deliveryattempt.FieldNotificationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.AttemptNumber(); ok {
		_spec.SetField(deliveryattempt.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNumber(); ok {
		_spec.AddField(deliveryattempt.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deliveryattempt.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(deliveryattempt.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(deliveryattempt.FieldHTTPStatus, field.TypeInt, value)
	}
	if _u.mutation.HTTPStatusCleared() {
		_spec.ClearField(deliveryattempt.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(deliveryattempt.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(deliveryattempt.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(deliveryattempt.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(deliveryattempt.FieldDurationMs, field.TypeInt64, value)
	}
	_node = &DeliveryAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deliveryattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
