// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/0xLaiHo/rc_tobias/ent/deliveryattempt"
	"github.com/0xLaiHo/rc_tobias/ent/notification"
	"github.com/0xLaiHo/rc_tobias/ent/outboxevent"
	"github.com/0xLaiHo/rc_tobias/ent/predicate"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDeliveryAttempt = "DeliveryAttempt"
	TypeNotification    = "Notification"
	TypeOutboxEvent     = "OutboxEvent"
)

// DeliveryAttemptMutation represents an operation that mutates the DeliveryAttempt nodes in the graph.
type DeliveryAttemptMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	notification_id   *uuid.UUID
	attempt_number    *int
	addattempt_number *int
	status            *deliveryattempt.Status
	http_status       *int
	addhttp_status    *int
	error_message     *string
	duration_ms       *int64
	addduration_ms    *int64
	created_at        *time.Time
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*DeliveryAttempt, error)
	predicates        []predicate.DeliveryAttempt
}

var _ ent.Mutation = (*DeliveryAttemptMutation)(nil)

// deliveryattemptOption allows management of the mutation configuration using functional options.
type deliveryattemptOption func(*DeliveryAttemptMutation)

// newDeliveryAttemptMutation creates new mutation for the DeliveryAttempt entity.
func newDeliveryAttemptMutation(c config, op Op, opts ...deliveryattemptOption) *DeliveryAttemptMutation {
	m := &DeliveryAttemptMutation{
		config:        c,
		op:            op,
		typ:           TypeDeliveryAttempt,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDeliveryAttemptID sets the ID field of the mutation.
func withDeliveryAttemptID(id uuid.UUID) deliveryattemptOption {
	return func(m *DeliveryAttemptMutation) {
		var (
			err   error
			once  sync.Once
			value *DeliveryAttempt
		)
		m.oldValue = func(ctx context.Context) (*DeliveryAttempt, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DeliveryAttempt.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDeliveryAttempt sets the old DeliveryAttempt of the mutation.
func withDeliveryAttempt(node *DeliveryAttempt) deliveryattemptOption {
	return func(m *DeliveryAttemptMutation) {
		m.oldValue = func(context.Context) (*DeliveryAttempt, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DeliveryAttemptMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DeliveryAttemptMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DeliveryAttempt entities.
func (m *DeliveryAttemptMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DeliveryAttemptMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DeliveryAttemptMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DeliveryAttempt.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNotificationID sets the "notification_id" field.
func (m *DeliveryAttemptMutation) SetNotificationID(u uuid.UUID) {
	m.notification_id = &u
}

// NotificationID returns the value of the "notification_id" field in the mutation.
func (m *DeliveryAttemptMutation) NotificationID() (r uuid.UUID, exists bool) {
	v := m.notification_id
	if v == nil {
		return
	}
	return *v, true
}

// OldNotificationID returns the old "notification_id" field's value of the DeliveryAttempt entity.
// If the DeliveryAttempt object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeliveryAttemptMutation) OldNotificationID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotificationID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotificationID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotificationID: %w", err)
	}
	return oldValue.NotificationID, nil
}

// ResetNotificationID resets all changes to the "notification_id" field.
func (m *DeliveryAttemptMutation) ResetNotificationID() {
	m.notification_id = nil
}

// SetAttemptNumber sets the "attempt_number" field.
func (m *DeliveryAttemptMutation) SetAttemptNumber(i int) {
	m.attempt_number = &i
	m.addattempt_number = nil
}

// AttemptNumber returns the value of the "attempt_number" field in the mutation.
func (m *DeliveryAttemptMutation) AttemptNumber() (r int, exists bool) {
	v := m.attempt_number
	if v == nil {
		return
	}
	return *v, true
}

// OldAttemptNumber returns the old "attempt_number" field's value of the DeliveryAttempt entity.
// If the DeliveryAttempt object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeliveryAttemptMutation) OldAttemptNumber(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttemptNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttemptNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttemptNumber: %w", err)
	}
	return oldValue.AttemptNumber, nil
}

// AddAttemptNumber adds i to the "attempt_number" field.
func (m *DeliveryAttemptMutation) AddAttemptNumber(i int) {
	if m.addattempt_number != nil {
		*m.addattempt_number += i
	} else {
		m.addattempt_number = &i
	}
}

// AddedAttemptNumber returns the value that was added to the "attempt_number" field in this mutation.
func (m *DeliveryAttemptMutation) AddedAttemptNumber() (r int, exists bool) {
	v := m.addattempt_number
	if v == nil {
		return
	}
	return *v, true
}

// ResetAttemptNumber resets all changes to the "attempt_number" field.
func (m *DeliveryAttemptMutation) ResetAttemptNumber() {
	m.attempt_number = nil
	m.addattempt_number = nil
}

// SetStatus sets the "status" field.
func (m *DeliveryAttemptMutation) SetStatus(d deliveryattempt.Status) {
	m.status = &d
}

// Status returns the value of the "status" field in the mutation.
func (m *DeliveryAttemptMutation) Status() (r deliveryattempt.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the DeliveryAttempt entity.
// If the DeliveryAttempt object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeliveryAttemptMutation) OldStatus(ctx context.Context) (v deliveryattempt.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *DeliveryAttemptMutation) ResetStatus() {
	m.status = nil
}

// SetHTTPStatus sets the "http_status" field.
func (m *DeliveryAttemptMutation) SetHTTPStatus(i int) {
	m.http_status = &i
	m.addhttp_status = nil
}

// HTTPStatus returns the value of the "http_status" field in the mutation.
func (m *DeliveryAttemptMutation) HTTPStatus() (r int, exists bool) {
	v := m.http_status
	if v == nil {
		return
	}
	return *v, true
}

// OldHTTPStatus returns the old "http_status" field's value of the DeliveryAttempt entity.
// If the DeliveryAttempt object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeliveryAttemptMutation) OldHTTPStatus(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHTTPStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHTTPStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHTTPStatus: %w", err)
	}
	return oldValue.HTTPStatus, nil
}

// AddHTTPStatus adds i to the "http_status" field.
func (m *DeliveryAttemptMutation) AddHTTPStatus(i int) {
	if m.addhttp_status != nil {
		*m.addhttp_status += i
	} else {
		m.addhttp_status = &i
	}
}

// AddedHTTPStatus returns the value that was added to the "http_status" field in this mutation.
func (m *DeliveryAttemptMutation) AddedHTTPStatus() (r int, exists bool) {
	v := m.addhttp_status
	if v == nil {
		return
	}
	return *v, true
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (m *DeliveryAttemptMutation) ClearHTTPStatus() {
	m.http_status = nil
	m.addhttp_status = nil
	m.clearedFields[deliveryattempt.FieldHTTPStatus] = struct{}{}
}

// HTTPStatusCleared returns if the "http_status" field was cleared in this mutation.
func (m *DeliveryAttemptMutation) HTTPStatusCleared() bool {
	_, ok := m.clearedFields[deliveryattempt.FieldHTTPStatus]
	return ok
}

// ResetHTTPStatus resets all changes to the "http_status" field.
func (m *DeliveryAttemptMutation) ResetHTTPStatus() {
	m.http_status = nil
	m.addhttp_status = nil
	delete(m.clearedFields, deliveryattempt.FieldHTTPStatus)
}

// SetErrorMessage sets the "error_message" field.
func (m *DeliveryAttemptMutation) SetErrorMessage(s string) {
	m.error_message = &s
}

// ErrorMessage returns the value of the "error_message" field in the mutation.
func (m *DeliveryAttemptMutation) ErrorMessage() (r string, exists bool) {
	v := m.error_message
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorMessage returns the old "error_message" field's value of the DeliveryAttempt entity.
// If the DeliveryAttempt object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeliveryAttemptMutation) OldErrorMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorMessage: %w", err)
	}
	return oldValue.ErrorMessage, nil
}

// ClearErrorMessage clears the value of the "error_message" field.
func (m *DeliveryAttemptMutation) ClearErrorMessage() {
	m.error_message = nil
	m.clearedFields[deliveryattempt.FieldErrorMessage] = struct{}{}
}

// ErrorMessageCleared returns if the "error_message" field was cleared in this mutation.
func (m *DeliveryAttemptMutation) ErrorMessageCleared() bool {
	_, ok := m.clearedFields[deliveryattempt.FieldErrorMessage]
	return ok
}

// ResetErrorMessage resets all changes to the "error_message" field.
func (m *DeliveryAttemptMutation) ResetErrorMessage() {
	m.error_message = nil
	delete(m.clearedFields, deliveryattempt.FieldErrorMessage)
}

// SetDurationMs sets the "duration_ms" field.
func (m *DeliveryAttemptMutation) SetDurationMs(i int64) {
	m.duration_ms = &i
	m.addduration_ms = nil
}

// DurationMs returns the value of the "duration_ms" field in the mutation.
func (m *DeliveryAttemptMutation) DurationMs() (r int64, exists bool) {
	v := m.duration_ms
	if v == nil {
		return
	}
	return *v, true
}

// OldDurationMs returns the old "duration_ms" field's value of the DeliveryAttempt entity.
// If the DeliveryAttempt object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeliveryAttemptMutation) OldDurationMs(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDurationMs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDurationMs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDurationMs: %w", err)
	}
	return oldValue.DurationMs, nil
}

// AddDurationMs adds i to the "duration_ms" field.
func (m *DeliveryAttemptMutation) AddDurationMs(i int64) {
	if m.addduration_ms != nil {
		*m.addduration_ms += i
	} else {
		m.addduration_ms = &i
	}
}

// AddedDurationMs returns the value that was added to the "duration_ms" field in this mutation.
func (m *DeliveryAttemptMutation) AddedDurationMs() (r int64, exists bool) {
	v := m.addduration_ms
	if v == nil {
		return
	}
	return *v, true
}

// ResetDurationMs resets all changes to the "duration_ms" field.
func (m *DeliveryAttemptMutation) ResetDurationMs() {
	m.duration_ms = nil
	m.addduration_ms = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *DeliveryAttemptMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DeliveryAttemptMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DeliveryAttempt entity.
// If the DeliveryAttempt object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeliveryAttemptMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DeliveryAttemptMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the DeliveryAttemptMutation builder.
func (m *DeliveryAttemptMutation) Where(ps ...predicate.DeliveryAttempt) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DeliveryAttemptMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DeliveryAttemptMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DeliveryAttempt, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DeliveryAttemptMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DeliveryAttemptMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DeliveryAttempt).
func (m *DeliveryAttemptMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DeliveryAttemptMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.notification_id != nil {
		fields = append(fields, deliveryattempt.FieldNotificationID)
	}
	if m.attempt_number != nil {
		fields = append(fields, deliveryattempt.FieldAttemptNumber)
	}
	if m.status != nil {
		fields = append(fields, deliveryattempt.FieldStatus)
	}
	if m.http_status != nil {
		fields = append(fields, deliveryattempt.FieldHTTPStatus)
	}
	if m.error_message != nil {
		fields = append(fields, deliveryattempt.FieldErrorMessage)
	}
	if m.duration_ms != nil {
		fields = append(fields, deliveryattempt.FieldDurationMs)
	}
	if m.created_at != nil {
		fields = append(fields, deliveryattempt.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DeliveryAttemptMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case deliveryattempt.FieldNotificationID:
		return m.NotificationID()
	case deliveryattempt.FieldAttemptNumber:
		return m.AttemptNumber()
	case deliveryattempt.FieldStatus:
		return m.Status()
	case deliveryattempt.FieldHTTPStatus:
		return m.HTTPStatus()
	case deliveryattempt.FieldErrorMessage:
		return m.ErrorMessage()
	case deliveryattempt.FieldDurationMs:
		return m.DurationMs()
	case deliveryattempt.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DeliveryAttemptMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case deliveryattempt.FieldNotificationID:
		return m.OldNotificationID(ctx)
	case deliveryattempt.FieldAttemptNumber:
		return m.OldAttemptNumber(ctx)
	case deliveryattempt.FieldStatus:
		return m.OldStatus(ctx)
	case deliveryattempt.FieldHTTPStatus:
		return m.OldHTTPStatus(ctx)
	case deliveryattempt.FieldErrorMessage:
		return m.OldErrorMessage(ctx)
	case deliveryattempt.FieldDurationMs:
		return m.OldDurationMs(ctx)
	case deliveryattempt.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown DeliveryAttempt field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeliveryAttemptMutation) SetField(name string, value ent.Value) error {
	switch name {
	case deliveryattempt.FieldNotificationID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotificationID(v)
		return nil
	case deliveryattempt.FieldAttemptNumber:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttemptNumber(v)
		return nil
	case deliveryattempt.FieldStatus:
		v, ok := value.(deliveryattempt.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case deliveryattempt.FieldHTTPStatus:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHTTPStatus(v)
		return nil
	case deliveryattempt.FieldErrorMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorMessage(v)
		return nil
	case deliveryattempt.FieldDurationMs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDurationMs(v)
		return nil
	case deliveryattempt.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown DeliveryAttempt field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DeliveryAttemptMutation) AddedFields() []string {
	var fields []string
	if m.addattempt_number != nil {
		fields = append(fields, deliveryattempt.FieldAttemptNumber)
	}
	if m.addhttp_status != nil {
		fields = append(fields, deliveryattempt.FieldHTTPStatus)
	}
	if m.addduration_ms != nil {
		fields = append(fields, deliveryattempt.FieldDurationMs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DeliveryAttemptMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case deliveryattempt.FieldAttemptNumber:
		return m.AddedAttemptNumber()
	case deliveryattempt.FieldHTTPStatus:
		return m.AddedHTTPStatus()
	case deliveryattempt.FieldDurationMs:
		return m.AddedDurationMs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeliveryAttemptMutation) AddField(name string, value ent.Value) error {
	switch name {
	case deliveryattempt.FieldAttemptNumber:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAttemptNumber(v)
		return nil
	case deliveryattempt.FieldHTTPStatus:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHTTPStatus(v)
		return nil
	case deliveryattempt.FieldDurationMs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDurationMs(v)
		return nil
	}
	return fmt.Errorf("unknown DeliveryAttempt numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DeliveryAttemptMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(deliveryattempt.FieldHTTPStatus) {
		fields = append(fields, deliveryattempt.FieldHTTPStatus)
	}
	if m.FieldCleared(deliveryattempt.FieldErrorMessage) {
		fields = append(fields, deliveryattempt.FieldErrorMessage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DeliveryAttemptMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DeliveryAttemptMutation) ClearField(name string) error {
	switch name {
	case deliveryattempt.FieldHTTPStatus:
		m.ClearHTTPStatus()
		return nil
	case deliveryattempt.FieldErrorMessage:
		m.ClearErrorMessage()
		return nil
	}
	return fmt.Errorf("unknown DeliveryAttempt nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DeliveryAttemptMutation) ResetField(name string) error {
	switch name {
	case deliveryattempt.FieldNotificationID:
		m.ResetNotificationID()
		return nil
	case deliveryattempt.FieldAttemptNumber:
		m.ResetAttemptNumber()
		return nil
	case deliveryattempt.FieldStatus:
		m.ResetStatus()
		return nil
	case deliveryattempt.FieldHTTPStatus:
		m.ResetHTTPStatus()
		return nil
	case deliveryattempt.FieldErrorMessage:
		m.ResetErrorMessage()
		return nil
	case deliveryattempt.FieldDurationMs:
		m.ResetDurationMs()
		return nil
	case deliveryattempt.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown DeliveryAttempt field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DeliveryAttemptMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DeliveryAttemptMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DeliveryAttemptMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DeliveryAttemptMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DeliveryAttemptMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DeliveryAttemptMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DeliveryAttemptMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown DeliveryAttempt unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DeliveryAttemptMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown DeliveryAttempt edge %s", name)
}

// NotificationMutation represents an operation that mutates the Notification nodes in the graph.
type NotificationMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	url              *string
	method           *string
	headers          *map[string]string
	body             *[]byte
	status           *notification.Status
	attempt_count    *int
	addattempt_count *int
	max_attempts     *int
	addmax_attempts  *int
	last_error       *string
	next_attempt_at  *time.Time
	created_at       *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*Notification, error)
	predicates       []predicate.Notification
}

var _ ent.Mutation = (*NotificationMutation)(nil)

// notificationOption allows management of the mutation configuration using functional options.
type notificationOption func(*NotificationMutation)

// newNotificationMutation creates new mutation for the Notification entity.
func newNotificationMutation(c config, op Op, opts ...notificationOption) *NotificationMutation {
	m := &NotificationMutation{
		config:        c,
		op:            op,
		typ:           TypeNotification,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNotificationID sets the ID field of the mutation.
func withNotificationID(id uuid.UUID) notificationOption {
	return func(m *NotificationMutation) {
		var (
			err   error
			once  sync.Once
			value *Notification
		)
		m.oldValue = func(ctx context.Context) (*Notification, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Notification.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNotification sets the old Notification of the mutation.
func withNotification(node *Notification) notificationOption {
	return func(m *NotificationMutation) {
		m.oldValue = func(context.Context) (*Notification, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NotificationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NotificationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Notification entities.
func (m *NotificationMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NotificationMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NotificationMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Notification.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetURL sets the "url" field.
func (m *NotificationMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *NotificationMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *NotificationMutation) ResetURL() {
	m.url = nil
}

// SetMethod sets the "method" field.
func (m *NotificationMutation) SetMethod(s string) {
	m.method = &s
}

// Method returns the value of the "method" field in the mutation.
func (m *NotificationMutation) Method() (r string, exists bool) {
	v := m.method
	if v == nil {
		return
	}
	return *v, true
}

// OldMethod returns the old "method" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldMethod(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMethod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMethod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMethod: %w", err)
	}
	return oldValue.Method, nil
}

// ResetMethod resets all changes to the "method" field.
func (m *NotificationMutation) ResetMethod() {
	m.method = nil
}

// SetHeaders sets the "headers" field.
func (m *NotificationMutation) SetHeaders(value map[string]string) {
	m.headers = &value
}

// Headers returns the value of the "headers" field in the mutation.
func (m *NotificationMutation) Headers() (r map[string]string, exists bool) {
	v := m.headers
	if v == nil {
		return
	}
	return *v, true
}

// OldHeaders returns the old "headers" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldHeaders(ctx context.Context) (v map[string]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeaders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeaders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeaders: %w", err)
	}
	return oldValue.Headers, nil
}

// ClearHeaders clears the value of the "headers" field.
func (m *NotificationMutation) ClearHeaders() {
	m.headers = nil
	m.clearedFields[notification.FieldHeaders] = struct{}{}
}

// HeadersCleared returns if the "headers" field was cleared in this mutation.
func (m *NotificationMutation) HeadersCleared() bool {
	_, ok := m.clearedFields[notification.FieldHeaders]
	return ok
}

// ResetHeaders resets all changes to the "headers" field.
func (m *NotificationMutation) ResetHeaders() {
	m.headers = nil
	delete(m.clearedFields, notification.FieldHeaders)
}

// SetBody sets the "body" field.
func (m *NotificationMutation) SetBody(b []byte) {
	m.body = &b
}

// Body returns the value of the "body" field in the mutation.
func (m *NotificationMutation) Body() (r []byte, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldBody(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ClearBody clears the value of the "body" field.
func (m *NotificationMutation) ClearBody() {
	m.body = nil
	m.clearedFields[notification.FieldBody] = struct{}{}
}

// BodyCleared returns if the "body" field was cleared in this mutation.
func (m *NotificationMutation) BodyCleared() bool {
	_, ok := m.clearedFields[notification.FieldBody]
	return ok
}

// ResetBody resets all changes to the "body" field.
func (m *NotificationMutation) ResetBody() {
	m.body = nil
	delete(m.clearedFields, notification.FieldBody)
}

// SetStatus sets the "status" field.
func (m *NotificationMutation) SetStatus(n notification.Status) {
	m.status = &n
}

// Status returns the value of the "status" field in the mutation.
func (m *NotificationMutation) Status() (r notification.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldStatus(ctx context.Context) (v notification.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *NotificationMutation) ResetStatus() {
	m.status = nil
}

// SetAttemptCount sets the "attempt_count" field.
func (m *NotificationMutation) SetAttemptCount(i int) {
	m.attempt_count = &i
	m.addattempt_count = nil
}

// AttemptCount returns the value of the "attempt_count" field in the mutation.
func (m *NotificationMutation) AttemptCount() (r int, exists bool) {
	v := m.attempt_count
	if v == nil {
		return
	}
	return *v, true
}

// OldAttemptCount returns the old "attempt_count" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldAttemptCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttemptCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttemptCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttemptCount: %w", err)
	}
	return oldValue.AttemptCount, nil
}

// AddAttemptCount adds i to the "attempt_count" field.
func (m *NotificationMutation) AddAttemptCount(i int) {
	if m.addattempt_count != nil {
		*m.addattempt_count += i
	} else {
		m.addattempt_count = &i
	}
}

// AddedAttemptCount returns the value that was added to the "attempt_count" field in this mutation.
func (m *NotificationMutation) AddedAttemptCount() (r int, exists bool) {
	v := m.addattempt_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetAttemptCount resets all changes to the "attempt_count" field.
func (m *NotificationMutation) ResetAttemptCount() {
	m.attempt_count = nil
	m.addattempt_count = nil
}

// SetMaxAttempts sets the "max_attempts" field.
func (m *NotificationMutation) SetMaxAttempts(i int) {
	m.max_attempts = &i
	m.addmax_attempts = nil
}

// MaxAttempts returns the value of the "max_attempts" field in the mutation.
func (m *NotificationMutation) MaxAttempts() (r int, exists bool) {
	v := m.max_attempts
	if v == nil {
		return
	}
	return *v, true
}

// OldMaxAttempts returns the old "max_attempts" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldMaxAttempts(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMaxAttempts is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMaxAttempts requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMaxAttempts: %w", err)
	}
	return oldValue.MaxAttempts, nil
}

// AddMaxAttempts adds i to the "max_attempts" field.
func (m *NotificationMutation) AddMaxAttempts(i int) {
	if m.addmax_attempts != nil {
		*m.addmax_attempts += i
	} else {
		m.addmax_attempts = &i
	}
}

// AddedMaxAttempts returns the value that was added to the "max_attempts" field in this mutation.
func (m *NotificationMutation) AddedMaxAttempts() (r int, exists bool) {
	v := m.addmax_attempts
	if v == nil {
		return
	}
	return *v, true
}

// ResetMaxAttempts resets all changes to the "max_attempts" field.
func (m *NotificationMutation) ResetMaxAttempts() {
	m.max_attempts = nil
	m.addmax_attempts = nil
}

// SetLastError sets the "last_error" field.
func (m *NotificationMutation) SetLastError(s string) {
	m.last_error = &s
}

// LastError returns the value of the "last_error" field in the mutation.
func (m *NotificationMutation) LastError() (r string, exists bool) {
	v := m.last_error
	if v == nil {
		return
	}
	return *v, true
}

// OldLastError returns the old "last_error" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldLastError(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastError: %w", err)
	}
	return oldValue.LastError, nil
}

// ClearLastError clears the value of the "last_error" field.
func (m *NotificationMutation) ClearLastError() {
	m.last_error = nil
	m.clearedFields[notification.FieldLastError] = struct{}{}
}

// LastErrorCleared returns if the "last_error" field was cleared in this mutation.
func (m *NotificationMutation) LastErrorCleared() bool {
	_, ok := m.clearedFields[notification.FieldLastError]
	return ok
}

// ResetLastError resets all changes to the "last_error" field.
func (m *NotificationMutation) ResetLastError() {
	m.last_error = nil
	delete(m.clearedFields, notification.FieldLastError)
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (m *NotificationMutation) SetNextAttemptAt(t time.Time) {
	m.next_attempt_at = &t
}

// NextAttemptAt returns the value of the "next_attempt_at" field in the mutation.
func (m *NotificationMutation) NextAttemptAt() (r time.Time, exists bool) {
	v := m.next_attempt_at
	if v == nil {
		return
	}
	return *v, true
}

// OldNextAttemptAt returns the old "next_attempt_at" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldNextAttemptAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNextAttemptAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNextAttemptAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNextAttemptAt: %w", err)
	}
	return oldValue.NextAttemptAt, nil
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (m *NotificationMutation) ClearNextAttemptAt() {
	m.next_attempt_at = nil
	m.clearedFields[notification.FieldNextAttemptAt] = struct{}{}
}

// NextAttemptAtCleared returns if the "next_attempt_at" field was cleared in this mutation.
func (m *NotificationMutation) NextAttemptAtCleared() bool {
	_, ok := m.clearedFields[notification.FieldNextAttemptAt]
	return ok
}

// ResetNextAttemptAt resets all changes to the "next_attempt_at" field.
func (m *NotificationMutation) ResetNextAttemptAt() {
	m.next_attempt_at = nil
	delete(m.clearedFields, notification.FieldNextAttemptAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *NotificationMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *NotificationMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *NotificationMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *NotificationMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *NotificationMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Notification entity.
// If the Notification object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotificationMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *NotificationMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the NotificationMutation builder.
func (m *NotificationMutation) Where(ps ...predicate.Notification) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NotificationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NotificationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Notification, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NotificationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NotificationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Notification).
func (m *NotificationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NotificationMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.url != nil {
		fields = append(fields, notification.FieldURL)
	}
	if m.method != nil {
		fields = append(fields, notification.FieldMethod)
	}
	if m.headers != nil {
		fields = append(fields, notification.FieldHeaders)
	}
	if m.body != nil {
		fields = append(fields, notification.FieldBody)
	}
	if m.status != nil {
		fields = append(fields, notification.FieldStatus)
	}
	if m.attempt_count != nil {
		fields = append(fields, notification.FieldAttemptCount)
	}
	if m.max_attempts != nil {
		fields = append(fields, notification.FieldMaxAttempts)
	}
	if m.last_error != nil {
		fields = append(fields, notification.FieldLastError)
	}
	if m.next_attempt_at != nil {
		fields = append(fields, notification.FieldNextAttemptAt)
	}
	if m.created_at != nil {
		fields = append(fields, notification.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, notification.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NotificationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case notification.FieldURL:
		return m.URL()
	case notification.FieldMethod:
		return m.Method()
	case notification.FieldHeaders:
		return m.Headers()
	case notification.FieldBody:
		return m.Body()
	case notification.FieldStatus:
		return m.Status()
	case notification.FieldAttemptCount:
		return m.AttemptCount()
	case notification.FieldMaxAttempts:
		return m.MaxAttempts()
	case notification.FieldLastError:
		return m.LastError()
	case notification.FieldNextAttemptAt:
		return m.NextAttemptAt()
	case notification.FieldCreatedAt:
		return m.CreatedAt()
	case notification.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NotificationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case notification.FieldURL:
		return m.OldURL(ctx)
	case notification.FieldMethod:
		return m.OldMethod(ctx)
	case notification.FieldHeaders:
		return m.OldHeaders(ctx)
	case notification.FieldBody:
		return m.OldBody(ctx)
	case notification.FieldStatus:
		return m.OldStatus(ctx)
	case notification.FieldAttemptCount:
		return m.OldAttemptCount(ctx)
	case notification.FieldMaxAttempts:
		return m.OldMaxAttempts(ctx)
	case notification.FieldLastError:
		return m.OldLastError(ctx)
	case notification.FieldNextAttemptAt:
		return m.OldNextAttemptAt(ctx)
	case notification.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case notification.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Notification field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotificationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case notification.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case notification.FieldMethod:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMethod(v)
		return nil
	case notification.FieldHeaders:
		v, ok := value.(map[string]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeaders(v)
		return nil
	case notification.FieldBody:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case notification.FieldStatus:
		v, ok := value.(notification.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case notification.FieldAttemptCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttemptCount(v)
		return nil
	case notification.FieldMaxAttempts:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMaxAttempts(v)
		return nil
	case notification.FieldLastError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastError(v)
		return nil
	case notification.FieldNextAttemptAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNextAttemptAt(v)
		return nil
	case notification.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case notification.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Notification field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NotificationMutation) AddedFields() []string {
	var fields []string
	if m.addattempt_count != nil {
		fields = append(fields, notification.FieldAttemptCount)
	}
	if m.addmax_attempts != nil {
		fields = append(fields, notification.FieldMaxAttempts)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NotificationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case notification.FieldAttemptCount:
		return m.AddedAttemptCount()
	case notification.FieldMaxAttempts:
		return m.AddedMaxAttempts()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotificationMutation) AddField(name string, value ent.Value) error {
	switch name {
	case notification.FieldAttemptCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAttemptCount(v)
		return nil
	case notification.FieldMaxAttempts:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMaxAttempts(v)
		return nil
	}
	return fmt.Errorf("unknown Notification numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NotificationMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(notification.FieldHeaders) {
		fields = append(fields, notification.FieldHeaders)
	}
	if m.FieldCleared(notification.FieldBody) {
		fields = append(fields, notification.FieldBody)
	}
	if m.FieldCleared(notification.FieldLastError) {
		fields = append(fields, notification.FieldLastError)
	}
	if m.FieldCleared(notification.FieldNextAttemptAt) {
		fields = append(fields, notification.FieldNextAttemptAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NotificationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NotificationMutation) ClearField(name string) error {
	switch name {
	case notification.FieldHeaders:
		m.ClearHeaders()
		return nil
	case notification.FieldBody:
		m.ClearBody()
		return nil
	case notification.FieldLastError:
		m.ClearLastError()
		return nil
	case notification.FieldNextAttemptAt:
		m.ClearNextAttemptAt()
		return nil
	}
	return fmt.Errorf("unknown Notification nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NotificationMutation) ResetField(name string) error {
	switch name {
	case notification.FieldURL:
		m.ResetURL()
		return nil
	case notification.FieldMethod:
		m.ResetMethod()
		return nil
	case notification.FieldHeaders:
		m.ResetHeaders()
		return nil
	case notification.FieldBody:
		m.ResetBody()
		return nil
	case notification.FieldStatus:
		m.ResetStatus()
		return nil
	case notification.FieldAttemptCount:
		m.ResetAttemptCount()
		return nil
	case notification.FieldMaxAttempts:
		m.ResetMaxAttempts()
		return nil
	case notification.FieldLastError:
		m.ResetLastError()
		return nil
	case notification.FieldNextAttemptAt:
		m.ResetNextAttemptAt()
		return nil
	case notification.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case notification.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Notification field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NotificationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NotificationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NotificationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NotificationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NotificationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NotificationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NotificationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Notification unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NotificationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Notification edge %s", name)
}

// OutboxEventMutation represents an operation that mutates the OutboxEvent nodes in the graph.
type OutboxEventMutation struct {
	config
	op              Op
	typ             string
	id              *uuid.UUID
	notification_id *uuid.UUID
	event_type      *string
	status          *outboxevent.Status
	scheduled_at    *time.Time
	stream_id       *string
	locked_by       *string
	locked_at       *time.Time
	last_error      *string
	published_at    *time.Time
	created_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*OutboxEvent, error)
	predicates      []predicate.OutboxEvent
}

var _ ent.Mutation = (*OutboxEventMutation)(nil)

// outboxeventOption allows management of the mutation configuration using functional options.
type outboxeventOption func(*OutboxEventMutation)

// newOutboxEventMutation creates new mutation for the OutboxEvent entity.
func newOutboxEventMutation(c config, op Op, opts ...outboxeventOption) *OutboxEventMutation {
	m := &OutboxEventMutation{
		config:        c,
		op:            op,
		typ:           TypeOutboxEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withOutboxEventID sets the ID field of the mutation.
func withOutboxEventID(id uuid.UUID) outboxeventOption {
	return func(m *OutboxEventMutation) {
		var (
			err   error
			once  sync.Once
			value *OutboxEvent
		)
		m.oldValue = func(ctx context.Context) (*OutboxEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().OutboxEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withOutboxEvent sets the old OutboxEvent of the mutation.
func withOutboxEvent(node *OutboxEvent) outboxeventOption {
	return func(m *OutboxEventMutation) {
		m.oldValue = func(context.Context) (*OutboxEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m OutboxEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m OutboxEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of OutboxEvent entities.
func (m *OutboxEventMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *OutboxEventMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *OutboxEventMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().OutboxEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNotificationID sets the "notification_id" field.
func (m *OutboxEventMutation) SetNotificationID(u uuid.UUID) {
	m.notification_id = &u
}

// NotificationID returns the value of the "notification_id" field in the mutation.
func (m *OutboxEventMutation) NotificationID() (r uuid.UUID, exists bool) {
	v := m.notification_id
	if v == nil {
		return
	}
	return *v, true
}

// OldNotificationID returns the old "notification_id" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldNotificationID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotificationID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotificationID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotificationID: %w", err)
	}
	return oldValue.NotificationID, nil
}

// ResetNotificationID resets all changes to the "notification_id" field.
func (m *OutboxEventMutation) ResetNotificationID() {
	m.notification_id = nil
}

// SetEventType sets the "event_type" field.
func (m *OutboxEventMutation) SetEventType(s string) {
	m.event_type = &s
}

// EventType returns the value of the "event_type" field in the mutation.
func (m *OutboxEventMutation) EventType() (r string, exists bool) {
	v := m.event_type
	if v == nil {
		return
	}
	return *v, true
}

// OldEventType returns the old "event_type" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldEventType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventType: %w", err)
	}
	return oldValue.EventType, nil
}

// ResetEventType resets all changes to the "event_type" field.
func (m *OutboxEventMutation) ResetEventType() {
	m.event_type = nil
}

// SetStatus sets the "status" field.
func (m *OutboxEventMutation) SetStatus(o outboxevent.Status) {
	m.status = &o
}

// Status returns the value of the "status" field in the mutation.
func (m *OutboxEventMutation) Status() (r outboxevent.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldStatus(ctx context.Context) (v outboxevent.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *OutboxEventMutation) ResetStatus() {
	m.status = nil
}

// SetScheduledAt sets the "scheduled_at" field.
func (m *OutboxEventMutation) SetScheduledAt(t time.Time) {
	m.scheduled_at = &t
}

// ScheduledAt returns the value of the "scheduled_at" field in the mutation.
func (m *OutboxEventMutation) ScheduledAt() (r time.Time, exists bool) {
	v := m.scheduled_at
	if v == nil {
		return
	}
	return *v, true
}

// OldScheduledAt returns the old "scheduled_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldScheduledAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScheduledAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScheduledAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScheduledAt: %w", err)
	}
	return oldValue.ScheduledAt, nil
}

// ResetScheduledAt resets all changes to the "scheduled_at" field.
func (m *OutboxEventMutation) ResetScheduledAt() {
	m.scheduled_at = nil
}

// SetStreamID sets the "stream_id" field.
func (m *OutboxEventMutation) SetStreamID(s string) {
	m.stream_id = &s
}

// StreamID returns the value of the "stream_id" field in the mutation.
func (m *OutboxEventMutation) StreamID() (r string, exists bool) {
	v := m.stream_id
	if v == nil {
		return
	}
	return *v, true
}

// OldStreamID returns the old "stream_id" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldStreamID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStreamID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStreamID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStreamID: %w", err)
	}
	return oldValue.StreamID, nil
}

// ClearStreamID clears the value of the "stream_id" field.
func (m *OutboxEventMutation) ClearStreamID() {
	m.stream_id = nil
	m.clearedFields[outboxevent.FieldStreamID] = struct{}{}
}

// StreamIDCleared returns if the "stream_id" field was cleared in this mutation.
func (m *OutboxEventMutation) StreamIDCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldStreamID]
	return ok
}

// ResetStreamID resets all changes to the "stream_id" field.
func (m *OutboxEventMutation) ResetStreamID() {
	m.stream_id = nil
	delete(m.clearedFields, outboxevent.FieldStreamID)
}

// SetLockedBy sets the "locked_by" field.
func (m *OutboxEventMutation) SetLockedBy(s string) {
	m.locked_by = &s
}

// LockedBy returns the value of the "locked_by" field in the mutation.
func (m *OutboxEventMutation) LockedBy() (r string, exists bool) {
	v := m.locked_by
	if v == nil {
		return
	}
	return *v, true
}

// OldLockedBy returns the old "locked_by" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldLockedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLockedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLockedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLockedBy: %w", err)
	}
	return oldValue.LockedBy, nil
}

// ClearLockedBy clears the value of the "locked_by" field.
func (m *OutboxEventMutation) ClearLockedBy() {
	m.locked_by = nil
	m.clearedFields[outboxevent.FieldLockedBy] = struct{}{}
}

// LockedByCleared returns if the "locked_by" field was cleared in this mutation.
func (m *OutboxEventMutation) LockedByCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldLockedBy]
	return ok
}

// ResetLockedBy resets all changes to the "locked_by" field.
func (m *OutboxEventMutation) ResetLockedBy() {
	m.locked_by = nil
	delete(m.clearedFields, outboxevent.FieldLockedBy)
}

// SetLockedAt sets the "locked_at" field.
func (m *OutboxEventMutation) SetLockedAt(t time.Time) {
	m.locked_at = &t
}

// LockedAt returns the value of the "locked_at" field in the mutation.
func (m *OutboxEventMutation) LockedAt() (r time.Time, exists bool) {
	v := m.locked_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLockedAt returns the old "locked_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldLockedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLockedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLockedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLockedAt: %w", err)
	}
	return oldValue.LockedAt, nil
}

// ClearLockedAt clears the value of the "locked_at" field.
func (m *OutboxEventMutation) ClearLockedAt() {
	m.locked_at = nil
	m.clearedFields[outboxevent.FieldLockedAt] = struct{}{}
}

// LockedAtCleared returns if the "locked_at" field was cleared in this mutation.
func (m *OutboxEventMutation) LockedAtCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldLockedAt]
	return ok
}

// ResetLockedAt resets all changes to the "locked_at" field.
func (m *OutboxEventMutation) ResetLockedAt() {
	m.locked_at = nil
	delete(m.clearedFields, outboxevent.FieldLockedAt)
}

// SetLastError sets the "last_error" field.
func (m *OutboxEventMutation) SetLastError(s string) {
	m.last_error = &s
}

// LastError returns the value of the "last_error" field in the mutation.
func (m *OutboxEventMutation) LastError() (r string, exists bool) {
	v := m.last_error
	if v == nil {
		return
	}
	return *v, true
}

// OldLastError returns the old "last_error" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldLastError(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastError: %w", err)
	}
	return oldValue.LastError, nil
}

// ClearLastError clears the value of the "last_error" field.
func (m *OutboxEventMutation) ClearLastError() {
	m.last_error = nil
	m.clearedFields[outboxevent.FieldLastError] = struct{}{}
}

// LastErrorCleared returns if the "last_error" field was cleared in this mutation.
func (m *OutboxEventMutation) LastErrorCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldLastError]
	return ok
}

// ResetLastError resets all changes to the "last_error" field.
func (m *OutboxEventMutation) ResetLastError() {
	m.last_error = nil
	delete(m.clearedFields, outboxevent.FieldLastError)
}

// SetPublishedAt sets the "published_at" field.
func (m *OutboxEventMutation) SetPublishedAt(t time.Time) {
	m.published_at = &t
}

// PublishedAt returns the value of the "published_at" field in the mutation.
func (m *OutboxEventMutation) PublishedAt() (r time.Time, exists bool) {
	v := m.published_at
	if v == nil {
		return
	}
	return *v, true
}

// OldPublishedAt returns the old "published_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldPublishedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublishedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublishedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublishedAt: %w", err)
	}
	return oldValue.PublishedAt, nil
}

// ClearPublishedAt clears the value of the "published_at" field.
func (m *OutboxEventMutation) ClearPublishedAt() {
	m.published_at = nil
	m.clearedFields[outboxevent.FieldPublishedAt] = struct{}{}
}

// PublishedAtCleared returns if the "published_at" field was cleared in this mutation.
func (m *OutboxEventMutation) PublishedAtCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldPublishedAt]
	return ok
}

// ResetPublishedAt resets all changes to the "published_at" field.
func (m *OutboxEventMutation) ResetPublishedAt() {
	m.published_at = nil
	delete(m.clearedFields, outboxevent.FieldPublishedAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *OutboxEventMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *OutboxEventMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *OutboxEventMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *OutboxEventMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *OutboxEventMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *OutboxEventMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the OutboxEventMutation builder.
func (m *OutboxEventMutation) Where(ps ...predicate.OutboxEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the OutboxEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *OutboxEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.OutboxEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *OutboxEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *OutboxEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (OutboxEvent).
func (m *OutboxEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *OutboxEventMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.notification_id != nil {
		fields = append(fields, outboxevent.FieldNotificationID)
	}
	if m.event_type != nil {
		fields = append(fields, outboxevent.FieldEventType)
	}
	if m.status != nil {
		fields = append(fields, outboxevent.FieldStatus)
	}
	if m.scheduled_at != nil {
		fields = append(fields, outboxevent.FieldScheduledAt)
	}
	if m.stream_id != nil {
		fields = append(fields, outboxevent.FieldStreamID)
	}
	if m.locked_by != nil {
		fields = append(fields, outboxevent.FieldLockedBy)
	}
	if m.locked_at != nil {
		fields = append(fields, outboxevent.FieldLockedAt)
	}
	if m.last_error != nil {
		fields = append(fields, outboxevent.FieldLastError)
	}
	if m.published_at != nil {
		fields = append(fields, outboxevent.FieldPublishedAt)
	}
	if m.created_at != nil {
		fields = append(fields, outboxevent.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, outboxevent.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *OutboxEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case outboxevent.FieldNotificationID:
		return m.NotificationID()
	case outboxevent.FieldEventType:
		return m.EventType()
	case outboxevent.FieldStatus:
		return m.Status()
	case outboxevent.FieldScheduledAt:
		return m.ScheduledAt()
	case outboxevent.FieldStreamID:
		return m.StreamID()
	case outboxevent.FieldLockedBy:
		return m.LockedBy()
	case outboxevent.FieldLockedAt:
		return m.LockedAt()
	case outboxevent.FieldLastError:
		return m.LastError()
	case outboxevent.FieldPublishedAt:
		return m.PublishedAt()
	case outboxevent.FieldCreatedAt:
		return m.CreatedAt()
	case outboxevent.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *OutboxEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case outboxevent.FieldNotificationID:
		return m.OldNotificationID(ctx)
	case outboxevent.FieldEventType:
		return m.OldEventType(ctx)
	case outboxevent.FieldStatus:
		return m.OldStatus(ctx)
	case outboxevent.FieldScheduledAt:
		return m.OldScheduledAt(ctx)
	case outboxevent.FieldStreamID:
		return m.OldStreamID(ctx)
	case outboxevent.FieldLockedBy:
		return m.OldLockedBy(ctx)
	case outboxevent.FieldLockedAt:
		return m.OldLockedAt(ctx)
	case outboxevent.FieldLastError:
		return m.OldLastError(ctx)
	case outboxevent.FieldPublishedAt:
		return m.OldPublishedAt(ctx)
	case outboxevent.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case outboxevent.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown OutboxEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OutboxEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case outboxevent.FieldNotificationID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotificationID(v)
		return nil
	case outboxevent.FieldEventType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventType(v)
		return nil
	case outboxevent.FieldStatus:
		v, ok := value.(outboxevent.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case outboxevent.FieldScheduledAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScheduledAt(v)
		return nil
	case outboxevent.FieldStreamID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStreamID(v)
		return nil
	case outboxevent.FieldLockedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLockedBy(v)
		return nil
	case outboxevent.FieldLockedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLockedAt(v)
		return nil
	case outboxevent.FieldLastError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastError(v)
		return nil
	case outboxevent.FieldPublishedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublishedAt(v)
		return nil
	case outboxevent.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case outboxevent.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *OutboxEventMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *OutboxEventMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OutboxEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown OutboxEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *OutboxEventMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(outboxevent.FieldStreamID) {
		fields = append(fields, outboxevent.FieldStreamID)
	}
	if m.FieldCleared(outboxevent.FieldLockedBy) {
		fields = append(fields, outboxevent.FieldLockedBy)
	}
	if m.FieldCleared(outboxevent.FieldLockedAt) {
		fields = append(fields, outboxevent.FieldLockedAt)
	}
	if m.FieldCleared(outboxevent.FieldLastError) {
		fields = append(fields, outboxevent.FieldLastError)
	}
	if m.FieldCleared(outboxevent.FieldPublishedAt) {
		fields = append(fields, outboxevent.FieldPublishedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *OutboxEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *OutboxEventMutation) ClearField(name string) error {
	switch name {
	case outboxevent.FieldStreamID:
		m.ClearStreamID()
		return nil
	case outboxevent.FieldLockedBy:
		m.ClearLockedBy()
		return nil
	case outboxevent.FieldLockedAt:
		m.ClearLockedAt()
		return nil
	case outboxevent.FieldLastError:
		m.ClearLastError()
		return nil
	case outboxevent.FieldPublishedAt:
		m.ClearPublishedAt()
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *OutboxEventMutation) ResetField(name string) error {
	switch name {
	case outboxevent.FieldNotificationID:
		m.ResetNotificationID()
		return nil
	case outboxevent.FieldEventType:
		m.ResetEventType()
		return nil
	case outboxevent.FieldStatus:
		m.ResetStatus()
		return nil
	case outboxevent.FieldScheduledAt:
		m.ResetScheduledAt()
		return nil
	case outboxevent.FieldStreamID:
		m.ResetStreamID()
		return nil
	case outboxevent.FieldLockedBy:
		m.ResetLockedBy()
		return nil
	case outboxevent.FieldLockedAt:
		m.ResetLockedAt()
		return nil
	case outboxevent.FieldLastError:
		m.ResetLastError()
		return nil
	case outboxevent.FieldPublishedAt:
		m.ResetPublishedAt()
		return nil
	case outboxevent.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case outboxevent.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OutboxEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *OutboxEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OutboxEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *OutboxEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OutboxEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *OutboxEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *OutboxEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown OutboxEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *OutboxEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown OutboxEvent edge %s", name)
}
