// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0xLaiHo/rc_tobias/ent/notification"
	"github.com/0xLaiHo/rc_tobias/ent/predicate"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetURL sets the "url" field.
func (_u *NotificationUpdate) SetURL(v string) *NotificationUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableURL(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *NotificationUpdate) SetMethod(v string) *NotificationUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMethod(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *NotificationUpdate) SetHeaders(v map[string]string) *NotificationUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *NotificationUpdate) ClearHeaders() *NotificationUpdate {
	_u.mutation.ClearHeaders()
	return _u
}

// SetBody sets the "body" field.
func (_u *NotificationUpdate) SetBody(v []byte) *NotificationUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *NotificationUpdate) ClearBody() *NotificationUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationUpdate) SetStatus(v notification.Status) *NotificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableStatus(v *notification.Status) *NotificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *NotificationUpdate) SetAttemptCount(v int) *NotificationUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableAttemptCount(v *int) *NotificationUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *NotificationUpdate) AddAttemptCount(v int) *NotificationUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *NotificationUpdate) SetMaxAttempts(v int) *NotificationUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMaxAttempts(v *int) *NotificationUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *NotificationUpdate) AddMaxAttempts(v int) *NotificationUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *NotificationUpdate) SetLastError(v string) *NotificationUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableLastError(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *NotificationUpdate) ClearLastError() *NotificationUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *NotificationUpdate) SetNextAttemptAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableNextAttemptAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *NotificationUpdate) ClearNextAttemptAt() *NotificationUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdate) SetUpdatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := notification.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Notification.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(notification.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(notification.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(notification.FieldHeaders, field.TypeJSON, value)
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(notification.FieldHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeBytes, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(notification.FieldBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(notification.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(notification.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(notification.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(notification.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(notification.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(notification.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(notification.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(notification.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetURL sets the "url" field.
func (_u *NotificationUpdateOne) SetURL(v string) *NotificationUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableURL(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *NotificationUpdateOne) SetMethod(v string) *NotificationUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMethod(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *NotificationUpdateOne) SetHeaders(v map[string]string) *NotificationUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *NotificationUpdateOne) ClearHeaders() *NotificationUpdateOne {
	_u.mutation.ClearHeaders()
	return _u
}

// SetBody sets the "body" field.
func (_u *NotificationUpdateOne) SetBody(v []byte) *NotificationUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *NotificationUpdateOne) ClearBody() *NotificationUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationUpdateOne) SetStatus(v notification.Status) *NotificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableStatus(v *notification.Status) *NotificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *NotificationUpdateOne) SetAttemptCount(v int) *NotificationUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableAttemptCount(v *int) *NotificationUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *NotificationUpdateOne) AddAttemptCount(v int) *NotificationUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *NotificationUpdateOne) SetMaxAttempts(v int) *NotificationUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMaxAttempts(v *int) *NotificationUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *NotificationUpdateOne) AddMaxAttempts(v int) *NotificationUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *NotificationUpdateOne) SetLastError(v string) *NotificationUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableLastError(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *NotificationUpdateOne) ClearLastError() *NotificationUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *NotificationUpdateOne) SetNextAttemptAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableNextAttemptAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *NotificationUpdateOne) ClearNextAttemptAt() *NotificationUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdateOne) SetUpdatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := notification.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Notification.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(notification.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(notification.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(notification.FieldHeaders, field.TypeJSON, value)
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(notification.FieldHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeBytes, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(notification.FieldBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(notification.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(notification.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(notification.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(notification.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(notification.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(notification.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(notification.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(notification.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
