// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/0xLaiHo/rc_tobias/ent/outboxevent"
	"github.com/google/uuid"
)

// OutboxEvent is the model entity for the OutboxEvent schema.
type OutboxEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// NotificationID holds the value of the "notification_id" field.
	NotificationID uuid.UUID `json:"notification_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Status holds the value of the "status" field.
	Status outboxevent.Status `json:"status,omitempty"`
	// ScheduledAt holds the value of the "scheduled_at" field.
	ScheduledAt time.Time `json:"scheduled_at,omitempty"`
	// StreamID holds the value of the "stream_id" field.
	StreamID string `json:"stream_id,omitempty"`
	// LockedBy holds the value of the "locked_by" field.
	LockedBy string `json:"locked_by,omitempty"`
	// LockedAt holds the value of the "locked_at" field.
	LockedAt *time.Time `json:"locked_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutboxEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outboxevent.FieldEventType, outboxevent.FieldStatus, outboxevent.FieldStreamID, outboxevent.FieldLockedBy, outboxevent.FieldLastError:
			values[i] = new(sql.NullString)
		case outboxevent.FieldScheduledAt, outboxevent.FieldLockedAt, outboxevent.FieldPublishedAt, outboxevent.FieldCreatedAt, outboxevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case outboxevent.FieldID, outboxevent.FieldNotificationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutboxEvent fields.
func (_m *OutboxEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outboxevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case outboxevent.FieldNotificationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field notification_id", values[i])
			} else if value != nil {
				_m.NotificationID = *value
			}
		case outboxevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case outboxevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = outboxevent.Status(value.String)
			}
		case outboxevent.FieldScheduledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_at", values[i])
			} else if value.Valid {
				_m.ScheduledAt = value.Time
			}
		case outboxevent.FieldStreamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stream_id", values[i])
			} else if value.Valid {
				_m.StreamID = value.String
			}
		case outboxevent.FieldLockedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locked_by", values[i])
			} else if value.Valid {
				_m.LockedBy = value.String
			}
		case outboxevent.FieldLockedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_at", values[i])
			} else if value.Valid {
				_m.LockedAt = new(time.Time)
				*_m.LockedAt = value.Time
			}
		case outboxevent.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case outboxevent.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case outboxevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case outboxevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutboxEvent.
// This includes values selected through modifiers, order, etc.
func (_m *OutboxEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OutboxEvent.
// Note that you need to call OutboxEvent.Unwrap() before calling this method if this OutboxEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OutboxEvent) Update() *OutboxEventUpdateOne {
	return NewOutboxEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OutboxEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OutboxEvent) Unwrap() *OutboxEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutboxEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OutboxEvent) String() string {
	var builder strings.Builder
	builder.WriteString("OutboxEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("notification_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotificationID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("scheduled_at=")
	builder.WriteString(_m.ScheduledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("stream_id=")
	builder.WriteString(_m.StreamID)
	builder.WriteString(", ")
	builder.WriteString("locked_by=")
	builder.WriteString(_m.LockedBy)
	builder.WriteString(", ")
	if v := _m.LockedAt; v != nil {
		builder.WriteString("locked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OutboxEvents is a parsable slice of OutboxEvent.
type OutboxEvents []*OutboxEvent
