// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0xLaiHo/rc_tobias/ent/outboxevent"
	"github.com/google/uuid"
)

// OutboxEventCreate is the builder for creating a OutboxEvent entity.
type OutboxEventCreate struct {
	config
	mutation *OutboxEventMutation
	hooks    []Hook
}

// SetNotificationID sets the "notification_id" field.
func (_c *OutboxEventCreate) SetNotificationID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetNotificationID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *OutboxEventCreate) SetEventType(v string) *OutboxEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableEventType(v *string) *OutboxEventCreate {
	if v != nil {
		_c.SetEventType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OutboxEventCreate) SetStatus(v outboxevent.Status) *OutboxEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableStatus(v *outboxevent.Status) *OutboxEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetScheduledAt sets the "scheduled_at" field.
func (_c *OutboxEventCreate) SetScheduledAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetScheduledAt(v)
	return _c
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableScheduledAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetScheduledAt(*v)
	}
	return _c
}

// SetStreamID sets the "stream_id" field.
func (_c *OutboxEventCreate) SetStreamID(v string) *OutboxEventCreate {
	_c.mutation.SetStreamID(v)
	return _c
}

// SetNillableStreamID sets the "stream_id" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableStreamID(v *string) *OutboxEventCreate {
	if v != nil {
		_c.SetStreamID(*v)
	}
	return _c
}

// SetLockedBy sets the "locked_by" field.
func (_c *OutboxEventCreate) SetLockedBy(v string) *OutboxEventCreate {
	_c.mutation.SetLockedBy(v)
	return _c
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableLockedBy(v *string) *OutboxEventCreate {
	if v != nil {
		_c.SetLockedBy(*v)
	}
	return _c
}

// SetLockedAt sets the "locked_at" field.
func (_c *OutboxEventCreate) SetLockedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetLockedAt(v)
	return _c
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableLockedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetLockedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *OutboxEventCreate) SetLastError(v string) *OutboxEventCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableLastError(v *string) *OutboxEventCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *OutboxEventCreate) SetPublishedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillablePublishedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OutboxEventCreate) SetCreatedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableCreatedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OutboxEventCreate) SetUpdatedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableUpdatedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OutboxEventCreate) SetID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableID(v *uuid.UUID) *OutboxEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_c *OutboxEventCreate) Mutation() *OutboxEventMutation {
	return _c.mutation
}

// Save creates the OutboxEvent in the database.
func (_c *OutboxEventCreate) Save(ctx context.Context) (*OutboxEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutboxEventCreate) SaveX(ctx context.Context) *OutboxEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutboxEventCreate) defaults() {
	if _, ok := _c.mutation.EventType(); !ok {
		v := outboxevent.DefaultEventType
		_c.mutation.SetEventType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := outboxevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ScheduledAt(); !ok {
		v := outboxevent.DefaultScheduledAt()
		_c.mutation.SetScheduledAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := outboxevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := outboxevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := outboxevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutboxEventCreate) check() error {
	if _, ok := _c.mutation.NotificationID(); !ok {
		return &ValidationError{Name: "notification_id", err: errors.New(`ent: missing required field "OutboxEvent.notification_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "OutboxEvent.event_type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OutboxEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := outboxevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScheduledAt(); !ok {
		return &ValidationError{Name: "scheduled_at", err: errors.New(`ent: missing required field "OutboxEvent.scheduled_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OutboxEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OutboxEvent.updated_at"`)}
	}
	return nil
}

func (_c *OutboxEventCreate) sqlSave(ctx context.Context) (*OutboxEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutboxEventCreate) createSpec() (*OutboxEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &OutboxEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(outboxevent.Table, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.NotificationID(); ok {
		_spec.SetField(outboxevent.FieldNotificationID, field.TypeUUID, value)
		_node.NotificationID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(outboxevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(outboxevent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ScheduledAt(); ok {
		_spec.SetField(outboxevent.FieldScheduledAt, field.TypeTime, value)
		_node.ScheduledAt = value
	}
	if value, ok := _c.mutation.StreamID(); ok {
		_spec.SetField(outboxevent.FieldStreamID, field.TypeString, value)
		_node.StreamID = value
	}
	if value, ok := _c.mutation.LockedBy(); ok {
		_spec.SetField(outboxevent.FieldLockedBy, field.TypeString, value)
		_node.LockedBy = value
	}
	if value, ok := _c.mutation.LockedAt(); ok {
		_spec.SetField(outboxevent.FieldLockedAt, field.TypeTime, value)
		_node.LockedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(outboxevent.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(outboxevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OutboxEventCreateBulk is the builder for creating many OutboxEvent entities in bulk.
type OutboxEventCreateBulk struct {
	config
	err      error
	builders []*OutboxEventCreate
}

// Save creates the OutboxEvent entities in the database.
func (_c *OutboxEventCreateBulk) Save(ctx context.Context) ([]*OutboxEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OutboxEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutboxEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutboxEventCreateBulk) SaveX(ctx context.Context) []*OutboxEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
