// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0xLaiHo/rc_tobias/ent/outboxevent"
	"github.com/0xLaiHo/rc_tobias/ent/predicate"
	"github.com/google/uuid"
)

// OutboxEventUpdate is the builder for updating OutboxEvent entities.
type OutboxEventUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxEventMutation
}

// Where appends a list predicates to the OutboxEventUpdate builder.
func (_u *OutboxEventUpdate) Where(ps ...predicate.OutboxEvent) *OutboxEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNotificationID sets the "notification_id" field.
func (_u *OutboxEventUpdate) SetNotificationID(v uuid.UUID) *OutboxEventUpdate {
	_u.mutation.SetNotificationID(v)
	return _u
}

// SetNillableNotificationID sets the "notification_id" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableNotificationID(v *uuid.UUID) *OutboxEventUpdate {
	if v != nil {
		_u.SetNotificationID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxEventUpdate) SetEventType(v string) *OutboxEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableEventType(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OutboxEventUpdate) SetStatus(v outboxevent.Status) *OutboxEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableStatus(v *outboxevent.Status) *OutboxEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *OutboxEventUpdate) SetScheduledAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableScheduledAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetStreamID sets the "stream_id" field.
func (_u *OutboxEventUpdate) SetStreamID(v string) *OutboxEventUpdate {
	_u.mutation.SetStreamID(v)
	return _u
}

// SetNillableStreamID sets the "stream_id" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableStreamID(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetStreamID(*v)
	}
	return _u
}

// ClearStreamID clears the value of the "stream_id" field.
func (_u *OutboxEventUpdate) ClearStreamID() *OutboxEventUpdate {
	_u.mutation.ClearStreamID()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *OutboxEventUpdate) SetLockedBy(v string) *OutboxEventUpdate {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableLockedBy(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *OutboxEventUpdate) ClearLockedBy() *OutboxEventUpdate {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *OutboxEventUpdate) SetLockedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableLockedAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *OutboxEventUpdate) ClearLockedAt() *OutboxEventUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboxEventUpdate) SetLastError(v string) *OutboxEventUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableLastError(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *OutboxEventUpdate) ClearLastError() *OutboxEventUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *OutboxEventUpdate) SetPublishedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillablePublishedAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *OutboxEventUpdate) ClearPublishedAt() *OutboxEventUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboxEventUpdate) SetUpdatedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_u *OutboxEventUpdate) Mutation() *OutboxEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutboxEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutboxEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboxEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboxevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutboxEventUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := outboxevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OutboxEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxevent.Table, outboxevent.Columns, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NotificationID(); ok {
		_spec.SetField(outboxevent.FieldNotificationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outboxevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(outboxevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(outboxevent.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StreamID(); ok {
		_spec.SetField(outboxevent.FieldStreamID, field.TypeString, value)
	}
	if _u.mutation.StreamIDCleared() {
		_spec.ClearField(outboxevent.FieldStreamID, field.TypeString)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(outboxevent.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(outboxevent.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(outboxevent.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(outboxevent.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(outboxevent.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(outboxevent.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(outboxevent.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutboxEventUpdateOne is the builder for updating a single OutboxEvent entity.
type OutboxEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxEventMutation
}

// SetNotificationID sets the "notification_id" field.
func (_u *OutboxEventUpdateOne) SetNotificationID(v uuid.UUID) *OutboxEventUpdateOne {
	_u.mutation.SetNotificationID(v)
	return _u
}

// SetNillableNotificationID sets the "notification_id" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableNotificationID(v *uuid.UUID) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetNotificationID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxEventUpdateOne) SetEventType(v string) *OutboxEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableEventType(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OutboxEventUpdateOne) SetStatus(v outboxevent.Status) *OutboxEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableStatus(v *outboxevent.Status) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *OutboxEventUpdateOne) SetScheduledAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableScheduledAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetStreamID sets the "stream_id" field.
func (_u *OutboxEventUpdateOne) SetStreamID(v string) *OutboxEventUpdateOne {
	_u.mutation.SetStreamID(v)
	return _u
}

// SetNillableStreamID sets the "stream_id" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableStreamID(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetStreamID(*v)
	}
	return _u
}

// ClearStreamID clears the value of the "stream_id" field.
func (_u *OutboxEventUpdateOne) ClearStreamID() *OutboxEventUpdateOne {
	_u.mutation.ClearStreamID()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *OutboxEventUpdateOne) SetLockedBy(v string) *OutboxEventUpdateOne {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableLockedBy(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *OutboxEventUpdateOne) ClearLockedBy() *OutboxEventUpdateOne {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *OutboxEventUpdateOne) SetLockedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableLockedAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *OutboxEventUpdateOne) ClearLockedAt() *OutboxEventUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboxEventUpdateOne) SetLastError(v string) *OutboxEventUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableLastError(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *OutboxEventUpdateOne) ClearLastError() *OutboxEventUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *OutboxEventUpdateOne) SetPublishedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillablePublishedAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *OutboxEventUpdateOne) ClearPublishedAt() *OutboxEventUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboxEventUpdateOne) SetUpdatedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_u *OutboxEventUpdateOne) Mutation() *OutboxEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutboxEventUpdate builder.
func (_u *OutboxEventUpdateOne) Where(ps ...predicate.OutboxEvent) *OutboxEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutboxEventUpdateOne) Select(field string, fields ...string) *OutboxEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OutboxEvent entity.
func (_u *OutboxEventUpdateOne) Save(ctx context.Context) (*OutboxEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxEventUpdateOne) SaveX(ctx context.Context) *OutboxEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutboxEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboxEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboxevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutboxEventUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := outboxevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OutboxEventUpdateOne) sqlSave(ctx context.Context) (_node *OutboxEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxevent.Table, outboxevent.Columns, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutboxEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboxevent.FieldID)
		for _, f := range fields {
			if !outboxevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outboxevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NotificationID(); ok {
		_spec.SetField(outboxevent.FieldNotificationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outboxevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(outboxevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(outboxevent.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StreamID(); ok {
		_spec.SetField(outboxevent.FieldStreamID, field.TypeString, value)
	}
	if _u.mutation.StreamIDCleared() {
		_spec.ClearField(outboxevent.FieldStreamID, field.TypeString)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(outboxevent.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(outboxevent.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(outboxevent.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(outboxevent.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(outboxevent.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(outboxevent.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(outboxevent.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxevent.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OutboxEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
