// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/0xLaiHo/rc_tobias/ent/deliveryattempt"
	"github.com/0xLaiHo/rc_tobias/ent/notification"
	"github.com/0xLaiHo/rc_tobias/ent/outboxevent"
	"github.com/0xLaiHo/rc_tobias/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deliveryattemptFields := schema.DeliveryAttempt{}.Fields()
	_ = deliveryattemptFields
	// deliveryattemptDescDurationMs is the schema descriptor for duration_ms field.
	deliveryattemptDescDurationMs := deliveryattemptFields[6].Descriptor()
	// deliveryattempt.DefaultDurationMs holds the default value on creation for the duration_ms field.
	deliveryattempt.DefaultDurationMs = deliveryattemptDescDurationMs.Default.(int64)
	// deliveryattemptDescCreatedAt is the schema descriptor for created_at field.
	deliveryattemptDescCreatedAt := deliveryattemptFields[7].Descriptor()
	// deliveryattempt.DefaultCreatedAt holds the default value on creation for the created_at field.
	deliveryattempt.DefaultCreatedAt = deliveryattemptDescCreatedAt.Default.(func() time.Time)
	// deliveryattemptDescID is the schema descriptor for id field.
	deliveryattemptDescID := deliveryattemptFields[0].Descriptor()
	// deliveryattempt.DefaultID holds the default value on creation for the id field.
	deliveryattempt.DefaultID = deliveryattemptDescID.Default.(func() uuid.UUID)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescURL is the schema descriptor for url field.
	notificationDescURL := notificationFields[1].Descriptor()
	// notification.URLValidator is a validator for the "url" field. It is called by the builders before save.
	notification.URLValidator = notificationDescURL.Validators[0].(func(string) error)
	// notificationDescMethod is the schema descriptor for method field.
	notificationDescMethod := notificationFields[2].Descriptor()
	// notification.DefaultMethod holds the default value on creation for the method field.
	notification.DefaultMethod = notificationDescMethod.Default.(string)
	// notificationDescAttemptCount is the schema descriptor for attempt_count field.
	notificationDescAttemptCount := notificationFields[6].Descriptor()
	// notification.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	notification.DefaultAttemptCount = notificationDescAttemptCount.Default.(int)
	// notificationDescMaxAttempts is the schema descriptor for max_attempts field.
	notificationDescMaxAttempts := notificationFields[7].Descriptor()
	// notification.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	notification.DefaultMaxAttempts = notificationDescMaxAttempts.Default.(int)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[10].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescUpdatedAt is the schema descriptor for updated_at field.
	notificationDescUpdatedAt := notificationFields[11].Descriptor()
	// notification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notification.DefaultUpdatedAt = notificationDescUpdatedAt.Default.(func() time.Time)
	// notification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notification.UpdateDefaultUpdatedAt = notificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
	outboxeventFields := schema.OutboxEvent{}.Fields()
	_ = outboxeventFields
	// outboxeventDescEventType is the schema descriptor for event_type field.
	outboxeventDescEventType := outboxeventFields[2].Descriptor()
	// outboxevent.DefaultEventType holds the default value on creation for the event_type field.
	outboxevent.DefaultEventType = outboxeventDescEventType.Default.(string)
	// outboxeventDescScheduledAt is the schema descriptor for scheduled_at field.
	outboxeventDescScheduledAt := outboxeventFields[4].Descriptor()
	// outboxevent.DefaultScheduledAt holds the default value on creation for the scheduled_at field.
	outboxevent.DefaultScheduledAt = outboxeventDescScheduledAt.Default.(func() time.Time)
	// outboxeventDescCreatedAt is the schema descriptor for created_at field.
	outboxeventDescCreatedAt := outboxeventFields[10].Descriptor()
	// outboxevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxevent.DefaultCreatedAt = outboxeventDescCreatedAt.Default.(func() time.Time)
	// outboxeventDescUpdatedAt is the schema descriptor for updated_at field.
	outboxeventDescUpdatedAt := outboxeventFields[11].Descriptor()
	// outboxevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	outboxevent.DefaultUpdatedAt = outboxeventDescUpdatedAt.Default.(func() time.Time)
	// outboxevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	outboxevent.UpdateDefaultUpdatedAt = outboxeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// outboxeventDescID is the schema descriptor for id field.
	outboxeventDescID := outboxeventFields[0].Descriptor()
	// outboxevent.DefaultID holds the default value on creation for the id field.
	outboxevent.DefaultID = outboxeventDescID.Default.(func() uuid.UUID)
}
