// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DeliveryAttempt is the predicate function for deliveryattempt builders.
type DeliveryAttempt func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// OutboxEvent is the predicate function for outboxevent builders.
type OutboxEvent func(*sql.Selector)
